### ISSUE TITLE
Exported options lost when modifying value for liba/libs target before lib target group

### ISSUE THREAD

**Issue by kamrann** [build2/build2#108]
### Context
```
# library buildfile

[usual stuff here]

liba{reprolib}: cxx.export.poptions += -Dfoo
libs{reprolib}: cxx.export.poptions += -Dfoo

lib{reprolib}:
{
  cxx.export.poptions += "-I$out_base" "-I$src_base/include"
}
```
### Observed
Source files compiled in a target which imports the above library inherit `-Dfoo` but not the `-I...` options.

### Expected
It's not entirely clear to me when and in what way variables set on both a target group and specific targets in that group are combined; however my expectation would be for the above to result in `cxx.export.poptions` on the imported target (for both static and shared) having the value `-Dfoo -I...`. They are combined as expected if the `liba{}`/`libs{}` assignments are moved below the `lib{}` block.

Attached is a full repro project, with additional notes inside `reprolib/buildfile`.
[build2-repro.zip](https://github.com/build2/build2/files/5506781/build2-repro.zip)

**Comment by boris-kolpackov** [comment]
While unfortunately error-prone, this is the expected behavior. The variable lookup hierarchy is:

```
target -> target group -> scope -> outer scope -> ... -> global scope
```

In the above example `liba{}` and `libs{}` are members of the `lib{}` target group. When you append to `poptions` on `liba{}`, the previous value is looked up but none is found (since nothing is yet set on `lib{}`). And once `poptions` on `liba{}` is set, that's the value that's used. If, however, you change the order:

```
lib{reprolib}:
{
  cxx.export.poptions += "-I$out_base" "-I$src_base/include"
}

liba{reprolib}: cxx.export.poptions += -Dfoo
libs{reprolib}: cxx.export.poptions += -Dfoo
```

The when appending to `poptions` on `liba{}`, the previous value is found in the target group.

**Comment by kamrann** [comment]
Understood, thanks. I'd assumed target and target group values were getting automatically merged in some way, I didn't realize it was a hard override.

This seems reasonably straightforward now you've spelled it out for me, but as you say it's potentially error-prone. Not sure how feasible it is but would be nice if there was a way to detect possible misuses and throw a warning; even if only for the simple cases like above.
