### ISSUE TITLE
Problems when importing installed libraries

### ISSUE THREAD

**Issue by jabra98** [build2/build2#126]
Hi, so I've played around a bit with build2 and when I tried to migrate one of my projects to it, I noticed that importing libraries behaves weirdly. 

This is how my buildfile looks:
```
libs = 
import libs += sfml-network%lib{hello} 
import libs += sfml-graphics%lib{hello} 

info "libs:" $libs

exe{hello}: {hxx ixx txx cxx}{**} $libs

cxx.poptions =+ "-I$out_root" "-I$src_root"

cxx.loptions =+ "-lpthread"

# commented out
#cxx.loptions =+ "-lsfml-network" "-lpthread"
#cxx.loptions =+ "-lsfml-window" "-lsfml-graphics" "-lsfml-system" "-lpthread"
```
and the message given by the `info` call is 
```
hello/hello/buildfile:5:1: info: libs: sfml-graphics%lib{hello} sfml-network%lib{hello}

``` 
as expected. But it seems that the libaries are still not correctly linked. This is the compiler invocation reported by the verbose option (full logs below):
```
clang++ -Wall -Wextra -std=c++2a -L /usr/local/lib -o hello-clang/hello/hello <bunch of .o files> /usr/lib64/libsfml-network.so /usr/lib64/libsfml-system.so /usr/lib64/libsfml-system.so /usr/lib64/libsfml-network.so /usr/lib64/libsfml-system.so /usr/lib64/libsfml-system.so /usr/lib64/libsfml-network.so /usr/lib64/libsfml-system.so /usr/lib64/libsfml-system.so
```
It seems that SFML's networking and systems libaries have successfully been forwarded to clang but the graphics library is missing. If I were to swap the order of the two `import libs` statements in the buildfile such that the graphics library is added first, the resulting compiler invocation is as followed:
```
clang++ -Wall -Wextra -lpthread -std=c++2a -L /usr/local/lib -o <bunch of .o files> /usr/lib64/libsfml-graphics.so /usr/lib64/libsfml-window.so /usr/lib64/libsfml-system.so /usr/lib64/libsfml-system.so /usr/lib64/libsfml-window.so /usr/lib64/libsfml-system.so /usr/lib64/libsfml-system.so /usr/lib64/libsfml-graphics.so /usr/lib64/libsfml-window.so /usr/lib64/libsfml-system.so /usr/lib64/libsfml-system.so /usr/lib64/libsfml-window.so /usr/lib64/libsfml-system.so /usr/lib64/libsfml-system.so

```
Now the graphics libraries are linked but `libsfml-network` is missing. 

It can be fixed by adding the missing one manually through `cxx.loptions` as I did in the commented-out part of the buildfile above.

What am I doing wrong? 

Here the full log files of the compiler invocations:
First the one where `import libs += sfml-network%lib{hello}` is on top:
https://pastebin.com/MHpgCKje

And here the other one:
https://pastebin.com/VEvjKsdA

**Comment by boris-kolpackov** [comment]
Thanks for the detailed description. This definitely smells like a bug. If these `sfml-*` libraries were installed from distribution packages, could you tell us the distribution so we can try to reproduce this? Also, could you attach the relevant `pkg-config` files (`sfml-{network,graphics,system}.pc, which are probably in `/usr/lib64/pkgconfig/`).

**Comment by jabra98** [comment]
I'm using Arch Linux and those packages were installed by the `sfml` package (from the official Arch repositories). I just went to look after those *.pc files and I noticed that there is also a `sfml-all.pc` package that fixes the issue. I'll attach it and the other ones aswell. 
[sfml_pc_files.tar.gz](https://github.com/build2/build2/files/5735779/sfml_pc_files.tar.gz)

**Comment by boris-kolpackov** [comment]
Thanks, looking at your `buildfile` again, specifically this fragment:

```
import libs += sfml-network%lib{hello} 
import libs += sfml-graphics%lib{hello} 
```

Can you try something like this instead:

```
import libs += sfml-network%lib{sfml-network} 
import libs += sfml-graphics%lib{sfml-graphics} 
```

I think what happens is because the target part (`lib{hello}`) is the same, after the project qualification is removed, they become the same target and the second occurrence is suppressed. If this is indeed what happens, we probably need to fix (or at least diagnose) this since it's unlikely but possible there will be identically-named libraries in several projects.

**Comment by jabra98** [comment]
Yeah that does work aswell. So is this the way to import system libraries then?

**Comment by boris-kolpackov** [comment]
Yes, in `build2` importation is a unified mechanism and the same import can be used to pick up a system-installed library in some configurations and a locally-built one in others, see: https://build2.org/build2/doc/build2-build-system-manual.xhtml#intro-import

In your (original) case, the reason `build2` was able to find the libraries even though they had bogus target names is because we also try the project name as a last resort when searching for the library binary. This is to handle cases like `zlib` where on some platforms the library is called `libz.*` and on others `zlib.*`.

**Comment by jabra98** [comment]
I see, thanks.
