### ISSUE TITLE
query build config

### ISSUE THREAD

**Issue by c30ra** [build2/build2#129]
Just wondering... it's possible to query any of the tools (b, bdep, bpkg) for information about project dependency

The reason I'm asking, is to know if it's possible to build an IDE plugin to get autocompletion.

**Comment by Klaim** [comment]
Yes there is some info through `b info` and `bdep status`.

However this is not enough for an IDE plugin because we need to have at least:
 - name of targets in projects/packages (at least the ones that seem important);
 - a description of the dependency graph would help to avoid having tools that guess it;
 - flags being used by each target in each config;
 just on the top of my head, but there is probably more.
 
(I did some research last year on the subject, I'm considering making VS and VSCode extensions, but I dont'have the time yet to launch that project, so don't hold your breath and feel free to start one if you can, I would gladly jump in the bandwagon of such project as soon as I can)


(note that issues should be for issues report, for discussion you can use the mailing list, cpplang's slack ... maybe the new community discussion feature of github would help too but it's not activated for this project)

**Comment by c30ra** [comment]
ok, thanks for the info, was thinking to vscode too 😂

**Comment by Klaim** [comment]
Also see #109 and [this mailing list thread](https://lists.build2.org/archives/users/2020-August/000849.html) :)

It's ok to open issues for requesting the things you need though, so if you want to start such extension, feel free to ask here for what's missing (what I pointed is not currently requested though we had some chat with Boris about that subject last year)
