### ISSUE TITLE
Support for custom source code generation process?

### ISSUE THREAD

**Issue by amorvincitomnia53** [build2/build2#154]
Often I'd like to use some custom source code generation process before compilation, such as executing a python script that outputs a header file to be included, or in a more complex case, compiling and executing some c++ code that outputs a c++ header file to be included.
Is there any support (or any plans for support) for custom source code generation process?
I can explicitly write down the dependency for the generation process, and I'd be glad if the build system can use that information to regenerate the header file when and only when it is necessary.
In the cases when I am using some external command (such as python) for code generation, I'm okay to make it a prerequisite to build the project.

**Comment by boris-kolpackov** [comment]
In `build2` source code generation is handled as part of the main build phase rather than as a special pre-build step. The easiest way to integrate a source code generator is with an ad hoc recipe, see this section in the 0.13.0 release announcement (and especially the `xxd` example) for details: https://build2.org/release/0.13.0.xhtml#adhoc-recipe

The other, more elaborate, option would be to write a build system module that provides a rule for the source code generator. Also, with the upcoming release, you will be able to do something in-between: an ad hoc rule.

**Comment by boris-kolpackov** [comment]
I am assuming this is addressed and closing the issue. If not, please feel free to reopen with additional information.
