### ISSUE TITLE
How configurable is project structure?

### ISSUE THREAD

**Issue by Iskustvo** [build2/build2#187]
First of all, thanks a lot for tackling all of modern C++ building/packaging issues and for tremendous effort put into this project!

This is the first build system since Make that gave me hope for a better tomorrow.
However, I'm questioning some decisions and I'd like to discuss/clarify them or find out how to achieve something closest to my desired project setup.

After running `bdep new -l c++,cpp -t lib,split libproject`, the project looks like this:
```
> tree -a -I .git* libproject
libproject/
├── .bdep
│   └── bdep.sqlite3
├── build
│   ├── bootstrap.build
│   ├── export.build
│   └── root.build
├── buildfile
├── include
│   └── libproject
│       ├── buildfile
│       ├── export.hpp
│       ├── project.hpp
│       └── version.hpp.in
├── manifest
├── README.md
├── repositories.manifest
├── src
│   └── libproject
│       ├── buildfile
│       └── project.cpp
└── tests
    ├── basics
    │   ├── buildfile
    │   └── driver.cpp
    ├── build
    │   ├── bootstrap.build
    │   └── root.build
    └── buildfile
```

There is quite a lot of clutter for this simplest project that I find quite unappealing.

1) `build` directory is traditionally used for the output of the build systems and it's quite misleading and unexpected to find it to be a config directory for `build2`.
In my opinion, much better name for it would be `build_config`, `build2_config` or something along the line. What do you think?

2) I have read in the documentaiton that creating build configurations/output anywhere inside of project is forbidden, but I still don't understand why?
It's one thing to forbid build configurations to be mixed with code, but I don't see any reason nor limitation not to have `build/{gcc,clang++,...}` configurations/output inside of self-contained project.

3) There are just too many "config" files scattered across the project, does it has to be that way?
Can't we group everything except `buildfile`s in (hidden) directorires to reduce the clutter?

4) Public `include` directory contains 3 generated headers just for the build system.
Do they have to be there for the installation (probably only for Windows)?
If yes, can we name them differently to distinguish them and ignore for non-Windows platforms?
If no, I would prefer to have configuration inside of some `buildfile` for that and expect `build2` to provide them for Windows builds.

5) I get that `build2`'s targets are directories and that's probably why each directory that has anything user-created also has `buildfile` and even additional configuration for it.
I assume this is done to give full control to the users who want for each directory to do different kind of magic and that's fine.
However, I'm wondering if these things could be done from top-level configuration in one place rather than having build files all over the project?
Can this be achieved by something like Make's target-specific variables (and in case of `build2`, target-specific configuration)?

For the reference, I would prefer following project structure:
```
ideal_libproject
├── README.md
├── include                                  # Public module interfaces ready for installation (with minimal clearly distinguished clutter).
│   └── ideal_libproject
│       ├── ideal_libproject.mpp
│       └── ...
├── src                                      # Source code for library and its tests.
│   ├── ideal_libproject
│   │   ├── ideal_libproject.cpp
│   │   └── ...
│   └── tests                                # Tests should probably follow same project structure if we want incremental testing.
│       ├── unit
│       │   ├── ideal_libproject_test.cpp
│       │   └── ...
│       └── ...
├── buildfile                                # Top-level configuration that describes rules for project subdirectories as well.
├── build2_config                            # Whole project/repository configuration.
│   ├── .hidden_build2_stuff                 # Hidden part of build2 stuff that shouldn't be touched.
│   │   └── ...
│   └── ...
└── build                                    # Build configurations for the project.
    ├── gcc
    │   └── ...                              # Should not contain "recursive" `build` and optionally top-level `ideal_libproject` directories.
    └── ...
```

Sorry for dumping all the questions/ideas like this!
It would be nice if you can help me understand what is reasonable (and already configurable) to expect and what isn't (and why).
Also, I don't mind helping out with the implementation.

**Comment by Klaim** [comment]
Hi, trying to answer the few questions which were already discussed. A lot of the answers are also part of `bdep help new` manual, so I would recommend reading that too for more details.

1) Its a common criticism. Using `alt-naming` (as in `-t lib,alt-naming,...`) will make this directory named `build2` instead, and also will make the `buildfile` files be named `build2file`, `*.build` files named `*.build2`.
`build2` have been supporting both naming conventions for some time with some constraints: you have to use the default or the alternative naming, but not both. The `manifest` file however cannot be named another ways (IMO unfortunate because `manifest` doesnt imply it's related to `build2`).

3) Not an answer but I should mention that `buildfile` you see everywhere are equivaletn to `makefile`, that's why you have them in a lot of directories. Then the number of directories can be reducd by using other setup like using `no-subdir` option to get the sources in the root directory.

4)
> Public include directory contains 3 generated headers just for the build system.

They are not "just for the buildsystem", the buildsystem doesnt care whatever headers you have. They are for convenience: a header for shared library symbol import/export, a header for library version defines which will automatically be up-to-date (the generated file is a template, the actual header will be generated in the build directory), and a header which is part of the "hello world" implementation set by default. See the `-t lib,no-version` to not generate the version header by default for example.

> Do they have to be there for the installation (probably only for Windows)?

No, this is just for convenience when creating a library project. A paackage can have whatever headers/sources you want, it's requirements are orthogonal to the source files you put in your projet.

> If yes, can we name them differently to distinguish them and ignore for non-Windows platforms?

You can just rename them manually and change the `buildfile` that might refer to it. 

I dont understand the mention of Windows here though, there is nothing platform-specific in there.

> If no, I would prefer to have configuration inside of some buildfile for that and expect build2 to provide them for Windows builds.

I still dont know why you refer to Windows build, but you should take a look into the buildfile, everything it does is commented. In any way you do whatever you want with its content so you could not have these headers if you want. For example when packaging projects which have already their own symbol export/import macro headers and version headers, I usuall just `bdep new` with options similar to the original project's structure, then remove the hell world files, then remove the version header template and the export header, comment/delete the related code in the `buildfile` then start to integrate the original code.

To clarify, usually the `buildfile` contains the description of the organisation of your project, it's not doing magic. The only exceptions are the location of the manifest file and the `build` directory and its content.

5) Yes, you can totally have just one buildfile with everything inside, there is no constraint. For example:
```
bdep new aaa -t lib,no-subdir,no-version,no-tests -l c++,cpp
```
Will create a flat directory without test directory or version header, and with just one buildfile.
There are other options you could add to not have git, the `repositories.manifest` etc.

I wonder if a `-t lib,simple` option that would gather all these options would be useful for beginners...

> Can this be achieved by something like Make's target-specific variables (and in case of build2, target-specific configuration)?

I'm not sure what you mean here.

**Comment by Klaim** [comment]
> For the reference, I would prefer following project structure:

I see no problem setting that up except:

- at best you will have the `build2` directory instead of `build2_config`
- the build configurations indeed need to be outside the **package**. If it was a mult-package project though you could have a build configuration directory in the root directory, as it would not be a package itself. Note that even if the build configuration directories were authorised inside a package directory, you would have to specify in the buildfile that these directories should not be taken into consideration.

**Comment by Iskustvo** [comment]
Thanks a lot for the quick answer!
It's kind of late now, but I'll try out your suggestions tomorrow and get back to you with a proper reply.

**Comment by Klaim** [comment]
Sorry for the lengh of this answer, I tried to be as thourough as possible. As pointed at the end, if you have questions you can also contact me directly by email if you want (or some other ways to chat)

About 2) I vaguely understand that the issue is in the complexity of detecting if projects are correclty setup or some other implementation-defined concerned, which is why I didn't answer that one. I think the build2 team is better placed to answer, if the documentation wasnt enough to understand.

About 3 and 4 : 

> First question is focused towards .bdep, multiple build2, manifest and repositories.manifest.
> Can't all these files/directories be stored into single top-level build/build2 directory?

Side note: If you were working on something simpler than an actual project, say a directory with a bunch of of C++ source files, and you didn't want to use dependency management, you could also just have 1 buildfile and that's it. But it wouldn't get you very far except for very toy stuffs. For a real project, you need to specify some more info which are separated here for the following reasons.

To answer:

- `.bdep` is a directory containing a database with the info of which config directories this project is initialized into, and other info that are necessary for `bdep` to work. You can totally ignore it, unless you are hitting some issues with your configurations. That directory might also contain future stuffs temporary for `bdep` to be working. 

- there is one `build` or `build2` directory per project/package and sub-project/package. By default if  you do `bdep new -t lib`, you get 2 of these, one for the whole package, one for the tests. The one for the tests helps with testing libraries: you want to make sure that when you run your tests it's possible to run them with a separately built binary of your library. To achieve this the tests are put in a sub-project (inheriting from most of the details of the outter project) from which we can generate a tests-only package which can be built separately with cli instructions to link with your library which would have been built previously. So this is just convenience for testing libraries, and it's also automatically use by `build2`'s CI (see `bdep ci` and `bdep help ci`) to make sure that your packaged library is actually usable (that you have set the proper flags for the user-side, etc.). Again this is just convenience by default, if you specify to not have tests you will have only one `build` directory.  Then the content of this directory is a bit more complex: the `root.build` file is basically what's automatically/implciitly included at the top of any `buildfile`. The `export.build` describes how to import targets from this package (I would argue this one could be removed and superseded by a default exporting mechanism, as described in #132). Then the `bootstrap.build` specify core things about the project that are needed by the build system because you will use build-system modules, so which ones? Note that I just talked about the build-system and not the package manager. The manifest is only used by the package manager for example. If you don't intend to use the package manager, thare are many files you could remove too. But basically every one of these files is consummed differently by different tools in the system, so I believe that's why they are separate (one could argue in the details but I never implemented such system so I don't know).
(side note: you might also want to check the `unit-tests` option in `bdep new` too)

-  `repositories.manifest` is, you might now start to guess it, a convenience: the goal is to have a pre-defined place where the package manager will look for addresses to repositories to look for packages the current package might depend upon. You can totally remove it without any effect other than when you initialize your project in an empty build configuration directory, the package manager will have no clue where to get the dependent pacakges, if any. You can then inform  it manually by doing `bpkg add <some-repository-git-or-like-cppget.org>` . That file is just there to avoid having to do that manually each time you initialize this package in another configuration directory. I often work with something like 6 to 8 configuration directories locally, CIs might even do more, and going these repository add commands manually would become insane (number of projects x number of dependencies which migth require pacakges in other repos x number of build configurations).
One might argue that it could be removed and implicitly the package manager should at least look into `cppget.org` for packages - or at least a user level config should specify default packages repositories, but it's actually more useful in the end if the projects specifiy where to find their dependencies. Also that way with private projects inside companies you can setup private repositories of packages and work internally with all your projects referring to only the packages in that repository. That's another exmaple I've actually had in the past.

> Second question is related solely to buildfiles.
> I get that they are equivalent to Makefiles, but with Make, you can have all logic in the single top-level Makefile.
> Having multiple Makefiles is optional.

Same with buildfiles, as I showed with my simplified `bdep new...` command.

> Can everything from multiple directory-specific buildfiles be achieved from the single top-level buildfile?

Yes, it just means that in that buildfile you will probably glob files recursively a lot, but that's the normal way to do it.

> As mentioned previously, I do want to have a nice project structure, but I also don't want to be forced to split build logic and would like it in the single top-level buildfile.

Personally I like to have one buildfile per directory that contains one or many binary targets (exe or lib, but not "just headers" except in header-only libraries). For example I don't like buildfiles in include directories. Some other like to have buildfiles even in include directories. If you look at packages in https://github.com/build2-packaging/ you will find a lot of varieties of ways to do it, and they all work. They just change what you put in the buildfiles.

There are mechanisms for including buildfiles into other buildfiles and there there is also a mechanism to specify in one buildfile the content of a virtual buidlfile in another directory (I dont remember the name of this thing but it's often useful to avoid creating buildfiles everywhere). And then there is the `build/root.build` file which can contain whatever buildfile specification that should be common to all buildfiles of the project. 
I dont see any limitation to organize however you want there.


About 5) : 
> Because I am working on gcc/clang and I have never used any macro to define symbols for importing/exporting.

Ok then I'm surprised because almost anyone having worked on library code had to deal with the symbol export/import dance and this header shows a typical example.  I'll explain: Using msvc, symbols must be explicitly exported and explicitly imported (this will detect symbol mismatches, which could be totally missed on unix or you might end up using symbols you didn't want to use). On gcc/clang, depending on the flags there is a default, which is often export-all. This is however considered bad practice because it conflat your binary files and exposes any function (or implicitly generated function) you didnt specify as static. So it's good practice to set gcc/clang to hidden symbols by default and then "mark" the functions and classes which are part of your binary API so that symbols are visible only for these.
These defines in the export header do the usual thing you'll find in pretty much any library which can be built as shared, so it's not specific to build2 projects at all, even cmake have a function to generate these. Here is how it works:
- there is a project-specific define that should be set to state thate we are building a shared library (because the samecode will often be compiled/linked in both static and shared libraries, so some things might have to be different, but usually only the symbol exporting/importing is important - hopefully) - if that define is not set, we can assume that we are building a static library. Or we can have an explicitly set other define to tell if we are building a static library. In any way, once the header is compiled, we know if we are compiling a static or shared library;
- there is a project-specific define that should be set if we are compiling translation units which are in this library, or translation unit from the user of this library, because that header will be compiled by both theimplementation and the user code. More on that coming.
- there is a project-specific define that should be put in front (more or less) of any symbol or class which should be part of the shared library interface and is not inline (I hope you understand well how C++ compilation/build works to get why...). Lets call this the api marker.
- the header will use these info to:
  - only export symbols if we are compiling a translation unit from the library implementation and we are in shared-library mode;
   - only import symbols if we are compilng a translation unit from the user's code and we are in shared-library mode;
   - dont import/export any symbol when building in static library;
   - on windows/msvc, code marked with the api marker will have the right compiler-specific instructions for doing either exporting or importing when using the shared library;
    - on gcc/clang, assuming that all symbols are hidden by default (because this is good practice), the api marker will be replaced only in exporting case (when compiling the library itself) by the "default" symbol visibility compiler intrinsic, which will make the symbol visible for consumption. The difference with windows/msvc is that there is nothing to do to import the symbol.
- the build-system scripts have the code that set the right defines to make the header do the right thing. In `build2` it looks like this: 
    ```makefile
    [...]
    # Using the defines for implementation build
    {hbmia obja}{*}: cxx.poptions += -DLIBXXX_STATIC_BUILD       # as static library
    {hbmis objs}{*}: cxx.poptions += -DLIBXXX_SHARED_BUILD     # as shared library
    [...]
    # The user's code will compile with these defines
    liba{xxx}: cxx.export.poptions += -DLIBXXX_STATIC                   # as static library
    libs{xxx}: cxx.export.poptions += -DLIBXXX_SHARED                 # as shared library
    ```
    As another example, often CMake projects will do somethiung like that (here extracted from `{fmt}`): 
    ```cmake
    if (BUILD_SHARED_LIBS)
       [...]
       target_compile_definitions(fmt PRIVATE FMT_EXPORT INTERFACE FMT_SHARED) // that define enable symbols export
     endif ()
    ```
    
    (note that the explicit importing/exporting of symbols of msvc is useful in making very visible some issues with shared libraries, which can be hidden if you never tried to build on more than unix platfosm, so even if you are in this situation it can be useful for issue detection).
    
If you look at various cross-platform C++ libraries, you'll find in headers the same mechanisms, or close.

> Obviously, these macros are defined only for Windows.

Yes because this is the "simplest" form of this mechanism, and assume that you export everything on non-windows, which is bad practice for cross-platform libraries. As soon as you want to hide symbols by default, you will have to add a few lines for the non-msvc case. (usually cases where the api marker will end up benig `__attribute__((visibility("default")))` on non-windows)

If you never want to compile on Windows OR your library should only exist as a static library or is header-only (aka "binless" in build2's terms), you don't need to use this header (nor the defines reffered also in the buildfile generated by default by `bdep new`). In every other cases you do, and might add the case for gcc/clang (see below).

Here are examples of well known non-build2 library projects doing this (all cross-platform libraries do this in some way or another):
 - `{fmt}`: https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h#L245
 - Boost libraries: https://www.boost.org/doc/libs/1_79_0/libs/config/doc/html/boost_config/boost_macro_reference.html#boost_config.boost_macro_reference.macros_for_libraries_with_separate_source_code.macros_controlling_shared_library_symbol_visibility
 - CMake's macro/function to generate a similar symbol export/import header (yes it's very common): https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html
 - Poco libraries: 
   - https://github.com/pocoproject/poco/blob/3fc3e5f5b8462f7666952b43381383a79b8b5d92/Util/include/Poco/Util/Util.h
   - https://github.com/pocoproject/poco/blob/3fc3e5f5b8462f7666952b43381383a79b8b5d92/PDF/include/Poco/PDF/zconf.h#L208
   - etc...
 - zlib: https://github.com/madler/zlib/search?q=dllexport
 - Qt : https://github.com/qt/qtbase/blob/b2233f19c9be9b87f4a49a4169aab6f5e7617563/src/corelib/global/qcompilerdetection.h#L131
 - OpenSSL: https://github.com/openssl/openssl/blob/e493d6e0ca4157741d2e4cfcb91fd367851f5771/include/openssl/e_os2.h#L180 (no idea if they try to hide the other symbols or if they use another mechanism as described below);
 - you can even search github for `dllexport` and see that they often appear in headers doing some define juggling similar to the export header, often more complex becasue of the clang/gcc case. 

Note that there are other mechanisms for handling symbol import/export, for example using msvc there is a system that allow to write a .def file listing the symbols to export, which is less intrusive by harder to keep current (depends a lot on the situation). Some projects use that. Some other projects ill use flags to just explicitly export everything not static. The export header is just the more common way.

> Furthermore, there is no-version option, but there isn't no-export because without this header, build probably won't work on Windows (I'm just guessing).

True that `no-export` is "missing" but it's also true that only very few libraries in packages will not be cross-platform. If you use `binless` for header-only libraries for examlpe there is no export header however. You can just delete the header and remove the lines in teh buildfile refering the the headers's define if you want, but yes that would make your library probably not working as shared library on windows, except if you opt-in another mechanism for symbol export/import.

> Unfortunately, I'm still unable to:
> - properly change public .hpp into .mpp module and have it working.

If you wanted to use modules, the devs are waiting for compilers to stabilize before adding another `bdep new` case which would generate module files.

However you can setup your project to use modules (though note that msvc support is disabled for now - they will reenable it as soon as they can - and that gcc will often not-link, so good luck 😬 ) manually after having used `bdep new`. Some time ago I setup a repository to demonstrate how to do it: 
 - modularize an exe starting from `bdep new`: https://github.com/Klaim/build2-helloworld-exe-modularized/commits/master
 - modularize a lib starting from `bdep new`: https://github.com/Klaim/build2-libhelloworld-exe-modularized/commits/master
Beware however:
  - this was made in an old version of build2 which was using the experimental module implementation of msvc, it will not work with `v0.14.0` or the stage version and msvc.
  - there might have been changes to `bdep new` generated projects in more recent versions of `build2`.

 Knowing that, the basic steps to use modules:
 - specify the module interface files extensions in `build/root.build` : `mxx{*}: extension = mpp` for example in yourcase
 - make sure your targets requires files which are module interface `mxx` target-type (see the commits, look for `mxx`)
 - make sure your module files are part of the package the same way headers would be (see commits)
 - use modules in the C++ code
 That's basically it.

> move tests to src/tests and to be able to run b test properly.

You can simply move the directory manually, then add the directory as a dependency in the buildfile in `src` (or the root). Nothing prevent that, and I believe even `bdep new` have an option to do that? I didn't try but at works you can move things around yourself, it's your buildfiles ;)
If you do so though maybe you don't want the tests to be in a sub-project? If you don't, delete the `build` directory in the `tests` directory. Anyway you can do as you want.

> If this is nobrainer for you, I would appreciate your help.

It's a no-brainer to setup a project like that after the `bdep new` command, with modifications. I could patch your project if you put it online, so that you see the steps I did. though it requires some understanding of whats happening in the buildfiles. Or maybe contact me directly by email ^^

**Comment by Iskustvo** [comment]
I'm incredibly grateful that you've explained everything with as many details as you have!

After reading all of this, one thing is obvious - Ignorance is bliss :D

As it seems that other than having the `build` directory inside of project, everything else is quite flexible and configurable, I'll just close this issue.

After filling the knowledge gap about symbols and good practices, I'll follow your examples and advices to build PoC project with C++ modules in desired project layout.
I'm pretty sure that I'll contact you by email at some point (if that doesn't become an issue) with some `build2` questions.
All in all, thanks a lot and enjoy the time before I start bothering you again :D

**Comment by Klaim** [comment]
> After reading all of this, one thing is obvious - Ignorance is bliss :D

I quite agree 🥲 

> All in all, thanks a lot and enjoy the time before I start bothering you again :D

Haha but I've been helping people around a lot these last years related to build2 so no worries, I'm used to do that. 👍🏽

**Comment by boris-kolpackov** [comment]
Just to add a few points to @Klaim excellent replies:

> 2. I have read in the documentaiton that creating build configurations/output anywhere inside of project is forbidden, but I still don't understand why?
It's one thing to forbid build configurations to be mixed with code, but I don't see any reason nor limitation not to have `build/{gcc,clang++,...}` configurations/output inside of self-contained project.

As @Klaim alluded to, `build2` supports fairly elaborate project structures (including subprojects/amalgamations, etc) and having a parallel (instead of potentially intersecting) src/our directory structure allows us to keep the complexity of determining "who is inside whom" (so to speak) at a (barely) manageable level.

Having said that, you can achieve pretty much what you want (while keeping `build2` happy) by "pushing" your project into a package subdirectory inside your project:

```
bdep new -t empty libproject # Or maybe just `project`.
cd libproject
bdep new --package  <...> libproject
```

Now you will be able to create build configurations inside `libproject/` (since it's no longer a build system project).

> 3. There are just too many "config" files scattered across the project, does it has to be that way?
> Can't we group everything except buildfiles in (hidden) directorires to reduce the clutter?

They are somewhat grouped: each project contains its own `build/` subdirectory where all its project-wide `buildfiles` are kept. What you probably don't (or didn't) realize is that you actually have two projects (in the build system sense): `libproject` and its `tests` subproject (`tests` is by default made a subproject so that it can be built independenly of your library in order to test the installed case).

Another thing to keep in mind is that the `build2` toolchain is a hierarchy of tools with the "base" tools (e.g., the build system) being usable without (and, in fact, having no knowledge of) higher-level tools (like the package/project manager). As a result, they use separate directories (though one could argue that seeing the they belong to the "`build2` toolchain", they could have shared the single `build2/` directory -- maybe we will get around to supporting this at some point).

Also let me add that while you clearly have/had other expectations about how a project should be structured, you approached it with an open mind, which is appreciated.

**Comment by Iskustvo** [comment]
Thanks @boris-kolpackov, I appreciate additional clarifications on the matter!

> As @Klaim alluded to, `build2` supports fairly elaborate project structures (including subprojects/amalgamations, etc) and having a parallel (instead of potentially intersecting) src/our directory structure allows us to keep the complexity of determining "who is inside whom" (so to speak) at a (barely) manageable level.

I understand. If it's possible at all, I still think it would be worth to try to allow such use-cases even if it ends up being only one hard-coded exception to the rule - something like `project_root/builds` where all build configurations/outputs for one project could live inside the project itself. What do you think, will adding that hard-coded exception also impose unbearable complexity to the whole toolchain?

> Having said that, you can achieve pretty much what you want (while keeping build2 happy) by "pushing" your project into a package subdirectory inside your project...

Thank you for the advice, but this feels like an inconvenient workaround. It's perfectly fine to rely on it now, at this stage, but I think it will be a real hindrance in the long run and that it might turn away potential users.

> though one could argue that seeing the they belong to the "`build2` toolchain", they could have shared the single `build2/` directory

Yeah, that's exactly my point. I understand that there are multiple independent (but nicely integrated) tools that we are referring to as `build2`. I would expect that anyone who uses one of these tools will very likely use most/all other tools as well (especially if packages could be downloaded as binaries instead of being limited to source code only). However, even if that's not the case, it still makes sense to group all `build2` toolchain configurations into a single `build2/` directory, and in it, we can logically separate files/directories for separate tools/purposes. In my opinion, this will drastically reduce the clutter in the project for someone who is using everything from `build2` toolchain.

> Also let me add that while you clearly have/had other expectations about how a project should be structured, you approached it with an open mind, which is appreciated.

I'll have to bookmark this one, no one ever said that I'm open-minded :smiley:
The remainder of this comment is not important for the discussion, it's about my background, so feel free to ignore it.

To be honest, I was writing generic `Make` build system for Linux-only libraries with features like auto-detection of all sources, perfectly structured `build/` directory with all `.objects/`, `.dependencies/`, `documentation/`, `coverage/` nicely split, with smart testing strategy where only necessary tests were rebuilt/rerun after their corresponding classes (sources that they are testing) have been changed and with optional support for incremental tests (because I hate mocking and would prefer that if I screw up some basic component, which fails all integration/non-mocked tests, that my build is able to give me the "smallest scope" of the tests which are failing to indicate where was the regression introduced). For that, I had to learn crapload of `Make` stuff (and also avoid convenient `GNU` extensions like your `.SECONDEXPANSION`), then I had to pray that it would be POSIX-compliant because there is no guarantee... When I researched C++20 modules, I realized that all of my `sed` parsing and features are now obsolete and have to be reimplemented (and that's when I found `build2` which is kind of `Make`-based but designed to simplify modern project struggles). I spent quite a lot of time and effort for that build system and the scope was only one platform and only simple library. For every mentioned feature, I had to make decision if I would restrict the project structure or drastically increase complexity in the code. Therefore, now that I see someone who is working on multiple tools (not just the build system), who is targeting all major platforms, who is supporting nested projects and on top of that most features that I wanted to have in my build system, I can definitely respect introduced limitations (though, as obvious from above, I would still try to find best compromise before just blindly accepting everything without understanding it first).

**Comment by boris-kolpackov** [comment]
> If it's possible at all, I still think it would be worth to try to allow such use-cases even if it ends up being only one hard-coded exception to the rule - something like `project_root/builds` where all build configurations/outputs for one project could live inside the project itself. What do you think, will adding that hard-coded exception also impose unbearable complexity to the whole toolchain?

Hard to say: the parallel src/out directory structure is pretty fundamental (and also by now quite ingrained) so we would need to audit every use of the relevant data (of which there is quite a bit) and make sure nothing breaks. We may still do this in the future but I first want to see if we can make the majority of users see the light, so to speak. Can you elaborate what makes you so attached to having your build output inside the project directory rather than, say, next to the project directory?

> To be honest, I was writing generic `Make` build system [...]

Yes, I've [been there, done that](https://codesynthesis.com/projects/build/). I did learn a lot (with many lessons incorporated into `build2`) but I can tell you without any hesitation (and regardless of whether you end up using `build2` or decide to continue with your own build system) that `make`/`shell`/`sed`/etc is a dead end, even if you don't care about Windows. The list of things we could do properly in `build2` and which we could only hope to hack around in `make` is very, very long.

**Comment by Iskustvo** [comment]
> Yes, I've [been there, done that](https://codesynthesis.com/projects/build/). I did learn a lot (with many lessons incorporated into `build2`) but I can tell you without any hesitation (and regardless of whether you end up using `build2` or decide to continue with your own build system) that `make`/`shell`/`sed`/etc is a dead end, even if you don't care about Windows. The list of things we could do properly in `build2` and which we could only hope to hack around in `make` is very, very long.

Yeah, from your videos on Youtube, it seemed fairly obvious that you went the same path as well. I came to the same conclusion. Nevertheless, this (`build2`) is the first build system since `Make` that I didn't hate immediately after the first look, because it follows the basic concept of user-defined `target: dependencies` rules and allows automatic detection of source files relieving the developers of the duty to constantly change the build files just for the sake of adding/removing some source files. Other features are greatly appreciated, but build system staying out of the developer's way once it's setup is most important for me. Second on the list is the simplicity and convenience, not necessarily as "Only few lines of code are needed to setup the build system in a project",  rather the fact that the configuration is concentrated in one place and easy to follow (As discussed above, allowing everything to be grouped in a single `build2` configuration directory would greatly help with this).

> Can you elaborate what makes you so attached to having your build output inside the project directory rather than, say, next to the project directory?

I cannot elaborate it better than @Klaim already [did](https://github.com/build2/build2/issues/187#issuecomment-1121184952).
To me, other than being surprising and "ugly", it just doesn't feel natural, nor familiar.
In general, I am not opposed to changing traditional things if it makes sense, but this one doesn't (from the user's perspective) and is just inconvenience. I really like the ideas/design of this toolchain and would like for it to become THE C++ build/package manager, but with so many alternatives, we should strive to make it more accessible without imposing such restrictions if we don't have to. Of course, "if we don't have to" question is left to you and core developers to decide if this is doable/maintainable in the long run.

**Comment by boris-kolpackov** [comment]
> the first build system since `Make` that I didn't hate immediately after the first look, because it follows the basic concept of user-defined `target: dependencies` rules [...]

Man, do you know how many people passionately hate `build2` for exactly this reason? ;-)

Regarding the build output dilemma, thanks to you both for the feedback. I think one situation where the "inside the project" approach falls apart (IMO) is when you start working on multiple independent projects (repositories) and you want them to share the build configuration (aka build directory), which is a common/recommended arrangement in `build2`. I think this can be traced back to the monorepo/multirepo debate: `build2` is firmly in the multirepo camp while CMake (and most other existing C/C++ build systems with the exception perhaps of `autotools`) are monorepo-oriented (i.e., if you have any external dependencies, you just fetch them into your project source directory).

Thoughts?

**Comment by Klaim** [comment]
> Man, do you know how many people passionately hate build2 for exactly this reason? ;-)

I can confirm that, unfortunately. I now avoid referencing `Make` directly when explaining `build2`'s base of syntax because people immediately think "ok it's like `make` so it will be as painful" 😬 , I now just explain that it's a `type{target} : requirements` based syntax and that's it.

The next source of hate is usually the short naming and then the syntax outside simple requirements. But I digress. 🥲 

> Thoughts?

I agree that this feature of being able to use multiple repositories in the same build configuration gives `build2` a massive advantages over, say CMake, and I even try to emphases this to potential new users when presenting `build2`. We need to be able to do that, it's crucial 👍🏽 .

But sometimes, all you want is work on a specific project you just cloned, build with a few configurations and that's it (for example when patching an already existing project, but there are a lot of other situations like that).
When I need to use multiple repos, I then setup my directories with build-configs in parent directory to the cloned project, but only then (or if I knew from the beginning).
The issue is mostly that you don't always need to use multiple repos, depends on the situation, and that can evolve too. Right now we "pay" for that feature even when we don't need it. It's not a big cost, mostly an annoyance we have to get used to (I'm used to it now) but it's still noise as pointed previously.

Ideally, I would prefer no restriction from tools on where the build-configurations can be located, let me decide, I know better - then being able to move them around as needed (I noticed `bdep config move` already helps with that, so only the in-project restriction prevent from total liberty right now). I would be ok with just a warning when creating build-configurations in-project (and a flag to silence it, if I want to do that in CI for example)

**Comment by boris-kolpackov** [comment]
> The issue is mostly that you don't always need to use multiple repos, depends on the situation

The "nightmare" scenario that I have in mind is when the user incrementally accumulates a large number of build configurations inside the project (I routinely end up with 5-10) and then realizes they need to share them with another repository. For example, as you've suggested, maybe you just need to fix a small bug in one of the dependencies and the need to share the configuration is actually temporary. So now you need to manually move your 5-10 configurations out of the project (and maybe move them back in once you are done). Also, moving the configurations will render your builds out-of-date, so you will end up with a complete rebuild.

I don't know, I feel like if we go this route, things will only get more confusing. And still the only "technical" reason for this that I see from the above discussion is "I am used to doing it like this".

But I think we do need a good FAQ entry explaining the rationale and also maybe a HOWTO entry that shows how to still achieve this with a sub-package approach (see [this thread](https://lists.build2.org/archives/users/2022-January /000937.html) for inspiration; notice also the "mini-monorepo" term used).

**Comment by Klaim** [comment]
> So now you need to manually move your 5-10 configurations out of the project (and maybe move them back in once you are done).

The directory move itself is easy if you used prefixes or subdirectories, I usually just `move build-* ../` but then yeah `bdep config move` doesnt help much with that. In projects where I need that many configurations locally (rarely, I let the CI work the other configs I don't need immediately) I write a script that create them so it's easy to just tweak the script and recreate the configurations- but it's not a move.

> Also, moving the configurations will render your builds out-of-date, so you will end up with a complete rebuild.

I didnt notice that when I moved some configs in the past, but it make sense.

Note that you are not forced to have these build configurations setup that way, nothing prevents you from always having them outside the build directory. Although I see your point.

> I don't know, I feel like if we go this route, things will only get more confusing. And still the only "technical" reason for this that I see from the above discussion is "I am used to doing it like this".

I would argue that the restriction also looks "arbitrary" to anyone just learning about it. So being it about habit or not (for me, being used to current `build2` restrictions, it *sometimes* feels more like "noise"), it's still a decision taken without considering the user's opinion - or at least it looks that way (I'm ignoring the technical details here, so that it's clear how it is perceived).

> But I think we do need a good FAQ entry explaining the rationale and also maybe a HOWTO entry that shows how to still achieve this with a sub-package approach (see [this thread](https://lists.build2.org/archives/users/2022-January/000937.html) for inspiration; notice also the "mini-monorepo" term used).

I agree it's a good first step and then it would allow gathering more opinion on the subject after the rationale is written down, see if that's enough to convince people to continue always have build configurations outside projects. If that's enough I wouldnt have more objections, but I am not convince it will prevent negative first impressions `^^;` I guess we'll see.
