### ISSUE TITLE
ci: "error: unable to import target mylib%lib{mylib}"

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#188]
```
bdep --version
bdep 0.14.0
libbpkg 0.14.0
libbutl 0.14.0
```

I'm seeing [this issue](
https://ci.cppget.org/@31009b0b-fbee-4a85-8a6e-9261074f01da/threadable/0.1.0-a.0.20220429185658.8833be2a19df/log/linux_debian_10-gcc_11.2-O3/public/0.14.0/test-installed) (scroll to bottom) when using the build2 ci on virtually all builds.

I created [a new project](https://github.com/helmesjo/threadable) using `bdep new -l c++ -t lib [...]`. I diffed it against [another build2 project](https://github.com/helmesjo/convertible) I have (which works fine) and really the only two noteworthy differences are that the former has `hxx{export}@./: cxx.importable = false` specified (which was autogenerated by `bdep` v0.14, and I tried removing it to no success), but also it has some more files under it's `./tests` subfolder (again, autogenerated). I suspect the `tests` diff is the trigger in this newer project since it does specify `import libs = threadable%lib{threadable}`.

**Unrelated question**
[`undefined reference to 'pthread_create'`](https://ci.cppget.org/@31009b0b-fbee-4a85-8a6e-9261074f01da/threadable/0.1.0-a.0.20220429185658.8833be2a19df/log/linux_debian_11-clang_13.0-static_O3/public/0.14.0/update)
Any tip on how to (using build2 practices) correctly setup so that consumers (including tests) link `pthread` (supporting gcc, clang, clang-apple, clang-emscripten etc)? Getting confused by `-pthread` & `-lpthread`, which goes to `cxx.coptions` or `cxx.loptions` or `cxx.libs` etc (google is not super clear, and want to avoid spamming the ci).

Thanks in advance!

**Comment by Klaim** [comment]
For the pthread issue take a look at many examples in our community packages where pthread is used (many are documented): https://github.com/search?q=org%3Abuild2-packaging+%22pthread%22+buildfile&type=code
For example in openssl: https://github.com/build2-packaging/openssl/blob/2e7506efa1f1015e9fd965b85c934cf3bc3014f9/openssl/openssl/buildfile#L85
Basically you have to add `-lpthread` to `c.libs` or `cxx.libs` or `cc.libs` for both, depending on the platform.

I'll take a look at your initial problem.

**Comment by helmesjo** [comment]
Thanks!

**Comment by Klaim** [comment]
Took me some time but it felt very familiar, this is actually a very very common issue:
 - in the `threadable/buildfile` you have executable targets defined with `./ : exe{...} : ...` which means they are requirements of the directory. Now this also means that any other target is NOT a requirement of the directory, including the library, but maybe it's requirements of other targets in the directory. Here the issue is that the library is a requirement of the executables so both are built when you build the project - but when the CI build the tests separately, it tries to get the library which should have been built and exported - but it was not built because the executable are not part of the distribution nor install! So basically it really cannot find the library because it didnt built the executable which would have built the library, and the library is not built "by default
  - when `./ : ` is not used in a `buildfile`, `build2` will assume that the first target explicitly defined in the `buildfile` is a requirement of the directory, which is why the `bdep new -t lib ...` generated project will build the library (the first target defined).
  
My recommandation is to always put `./ : ` either at the top and list the different targets which must be built, or at the beginning of the first line defining the requirements of the targets which much be built.
I used this last solution to make sure the library is always built and it seems to fix the issue. See this pull request https://github.com/helmesjo/threadable/pull/1

**Comment by helmesjo** [comment]
@Klaim Ah, thank you! I did notice the "missing" `./:` for the library but read the docs wrong and assumed that if it's not added _to the first target_ it will be implicitly added, but if I understand you correctly it's only implicitly added to the first target _if it's not added to any of the targets_.

Does this mean that the autogenerated buildfile should really always add it to the first "main" target? To be explicit, that is. I guess the mistake I did was to snag the tests-part from the other project (which does have the `./:` for the main target).

Sorry for rewriting the history, wasn't expecting anyone to be working in the repo... (: I'll cherry-pick your changes and see what I get!

Thanks agian!

**Comment by Klaim** [comment]
> Does this mean that the autogenerated buildfile should really always add it to the first "main" target? 

My personal opinion is that this rule is problematic because it's basically a rule and an exception instead of a consistent rule. I would prefer that dependency to the directory be either not-by-default + explicit opt-in OR by-default + explicit opt-out, but not a weird mix.
We already discussed this several time in the past with Boris (devteam) but if my memory is correct he disagrees because people used to make are used to that rule; or it's a bit too late to change (because of the existing packages that would be broken if that rule would change now). So I personally see it as a design bug (in particular because through the years it made me lose a lot of time) but opinions may vary.

As a "workaround" I try to be explicit all the time with requirements to directory.

> Sorry for rewriting the history, wasn't expecting anyone to be working in the repo... (: I'll cherry-pick your changes and see what I get!

No problem, as long as you can reproduce the fix it's ok to me.

**Comment by helmesjo** [comment]
@Klaim Regarding the tests, is there (hypothetically speaking) any way to not build them during `bdep update`, and only with `bdep test` (I tested to not have `./:` for them but then `bdep test` just skipped them)? Otherwise, when exactly would you _not_ make a target a requirement of the directory (`./:`)? (I feel like I'm definitely missing some basic knowledge here, so feel free to just send me to a relevant section of the docs).
In this (header-only) case it makes little sense to not build the test of course, because you want at least some verification of success.

**Comment by Klaim** [comment]
> Regarding the tests, is there (hypothetically speaking) any way to not build them during bdep update, and only with bdep test (I tested to not have ./: for them but then bdep test just skipped them)?

Your question have some ambiguity because in yuor project you have set some test executable in the directory which is supposed to have only the library (ideally, not obligated but you'll see why I'm saying this in a minute).

`bdep update` will build the root directory of the project, then in the root `buildfile` the first line will basically say that the requirement is to build all the sub-directories except the `build` one: 
```
./: {*/ -build/} doc{README.md} manifest
```

So it means that you could also have your tests (the one in `threadable/` ) in a separate directory and mark it as to-be-ignored-by-default:
```
./: {*/ -build/ -benchmarks/} doc{README.md} manifest
```

If you do this, then the buildfile in that `benchmarks/` directory will only be considered IFF you explicitly do something with it, for example (using directly the buildsystem):
```
b benchmark/  # OR ....
b update: benchmark/  # OR if you wanted to do something else:
b clean: benchmark/
```

Not making a target a requirement of the directory, just means it will not be built when building the directory (or taken into account with other operations). In the same way than just before, if the target is not explicitly required to the directory, then building it needs to be requested throught he command (or as part as a requirement):
```
b threadable/lib{threadable}  # builds the library which was not built, OR...
b update: threadable/lib{threadable} # etc.
```
(note that for your header-only library, this will just generate the version header etc. in the build configuration directory)

See [this doc](https://build2.org/build2/doc/b.xhtml) for more about this syntax - this is not available with `bdep`, see https://github.com/build2/build2/issues/84

However, in general it's better to keep the "normal" tests always requirements by default (as the default generated project does). This is because:
- if you are developping on the project, you will clone the project and then build + test, so you need to do that in like one or two commands, which means not haveing to figure out the exact invocation and location of the tests. Then only if it's special tests (benchmarking maybe) you will set it up to not build these tests by moving them in a directory which is not required by default - I 've done that in the past in projects which had massive benchmark test suite for example;
- if you are a user of the package, your project depends on that library: then even if the package contains the sources of the tests (usually it does, or at least there is a related package with the sources for the tests), the tests will never be built unless you explicitly require it either by using the previous commands (but targeting the build configuration directories instead of the build directories) or by doing `bdep test --recursive` or `--immediate` which require to test the dependencies (recursively or only the immediate dependencies, respectively), in which case they will be built.

So as a developer of the project you do need these tests anyway, and build2 will not build them for your user, automatically. 

> Otherwise, when exactly would you not make a target a requirement of the directory (./:)?

The few situations where I would do this:
- the target is an implementation detail of how to build the project: for example in your buildfile there is a `libue{doctest_main}` which is just required to build the executables, it's not needed for the users (and it would be problematic to expose it to users too).
- the target is for "extra" usage, like your benchmarks. In that case I prefer to do it by putting them in a directory which is not required by default ,but you could also not require these executables by default. In that case the user have to know the name of the executables to build or test them, which can be cumbersome compared to just knowing where the directory with these is.

Another point related to your questions and the organization of your project: your tests (which are more benchmark tests) use google-benchmark which is quite a big dependency that your users will have to get too because it's set as a normal dependency in your manifest. To avoid users having to dowload dependencies for tests of their dependencies, we tend, in these cases, to move the tests in another package which have the dependencies for the tests. This is done by using build2's capability to handle multiple packages in the same (git) repository + a special naming scheme for packages so that the CI knows which package contains tests for which package.  If you are not familiar with the multi-package repositories, read the doc of `[bdep help new`](https://build2.org/bdep/doc/bdep-new.xhtml). Also read this [How To](https://github.com/build2/HOWTO/blob/master/entries/handle-tests-with-extra-dependencies.md)

So my recommendation Ideally:
- make your repository as a multi-package repository (you'll have to add a directory over the project directory, see the How To link);
- in addition to your library package, create a test package. If you think the benchmarks should be separated from the tests, maybe create a benchmark package too;
- setup the package dependencies so that the test packages are clearly related to the library package (follow the info in the How To);
This way you dont even need to care if targets should be requirements or not, they are separated in separate packages, the user can decide to bring them or not.

Meanwhile, if you need to progress without splitting the project into multiple packages, I would recommend:
- move actual test code/exes into the `tests/` directory and make sure its a default requirement of the root directory (which is already the case if you didnt'change the root buildfile);
- move the benchmark in a separate `benchmark/` directory, and decide if you want it to not be built by default. If so, add the `-benchmark/` bit in the root buildfile (see my example around the beginning of this post). Then when you want to run the benchmarks, do `b test: benchmarks/` for example.

Finally, feel free to ask questions about all this and how to proceed with your projects etc. but maybe either do it in on of the community chat (see [this page](https://build2.org/community.xhtml#help)), directly by emailing me or  (as we starting to gooff-topic here) or maybe issue tickets in your project if the questions are specific toyour project.
In any way I'm happy to help 👍🏽

**Comment by helmesjo** [comment]
@Klaim A lot more thorough than I expected, greatly appreciated! Now I got some reading (and restructuring) to do. (:

**Comment by boris-kolpackov** [comment]
> Btw, the invite link doesn't appear to work

Ah, they broke it again. Could you try to follow a link from https://cppalliance.org/slack/ and let me know if that works (so that I can update other places)?

> Basically you have to add `-lpthread` to `c.libs` or `cxx.libs` or `cc.libs` for both, depending on the platform.

More precisely, you would want to add `-lpthread` to `*.libs` (unless on Windows) if it's an implementation dependency (i.e., you only refer to the pthread API in your source files) and to `*.libs` as well as `*.export.libs` if it's an interface dependency (i.e., you also refer to it in header/inline files, including if it's a header-only library, naturally).

> Regarding the tests, is there (hypothetically speaking) any way to not build them during `bdep update`, and only with `bdep test` [...]

There is in 0.15.0:

```
./: exe{test}: update = false
exe{test}: test = true
```

> My personal opinion is that this rule is problematic because it's basically a rule and an exception instead of a consistent rule. I would prefer that dependency to the directory be either not-by-default + explicit opt-in OR by-default + explicit opt-out, but not a weird mix.
> We already discussed this several time in the past with Boris (devteam) but if my memory is correct he disagrees because people used to make are used to that rule; or it's a bit too late to change (because of the existing packages that would be broken if that rule would change now). So I personally see it as a design bug (in particular because through the years it made me lose a lot of time) but opinions may vary.

The idea behind the current semantics is that if you don't specify the default target(s) explicitly, then the first one is assumed. Which is handy for simple `buildfiles` that are often found in tests:

```
exe{driver}: cxx{driver}
```

Note that while now the explicit alternative is not that much worse:

```
./: exe{driver}: cxx{driver}
```

This rule chaining support was a relatively recent addition and before that it would have been a much uglier and more repetitive:

```
./: exe{driver}
exe{driver}: cxx{driver}
```

Probably if things happened the other way around (chaining first, default target second), we wouldn't have made the same decision. But feel free to file a bug report for this: we can always make this semantics configurable on the per-project basis.

**Comment by Klaim** [comment]
> There is in 0.15.0:
> 
> ```
> ./: exe{test}: update = false
> exe{test}: test = true
> ```

Interesting!

>  But feel free to file a bug report for this: we can always make this semantics configurable on the per-project basis.

Noted, I will when I find the time. 👍🏽

**Comment by helmesjo** [comment]
> > Btw, the invite link doesn't appear to work
> 
> Ah, they broke it again. Could you try to follow a link from https://cppalliance.org/slack/ and let me know if that works (so that I can update other places)?
> 
Yep, that worked. Thanks!

> > Regarding the tests, is there (hypothetically speaking) any way to not build them during `bdep update`, and only with `bdep test` [...]
> 
> There is in 0.15.0:
> 
> ```
> ./: exe{test}: update = false
> exe{test}: test = true
> ```
> 
Ah great, precisely what I was thinking of.
