### ISSUE TITLE
Skip executing compilation while printing commands

### ISSUE THREAD

**Issue by Ankur-deDev** [build2/build2#21]
In order to produce a compilation database I am using the following command provided by a community member (from [here](https://lists.build2.org/archives/users/2018-September/000421.html)):
`$ b -v |& compiledb  
`

In some cases, I do not need to actually do the compilation so I would like to speed up this process.
Is there an easy way to have build2 (0.10.0) skip executing the compile commands and only print them?

I tried with --match-only option, but this does not produce any output.

Thanks for your help.

**Comment by boris-kolpackov** [comment]
There is no way currently and implementing this will be a bit tricky.

Specifically, some commands may not be *dry-run'able*. For example, we won't be able to skip regenerating a missing or outdated auto-generated header because the result is used as an input to the DAG. And the rabbit hole goes deeper: regenerating such a header may require building the generator which we also cannot skip. As a result, a rule cannot just check some flag and skip executing the command. This can only be done once when we are in the final execute phase (as opposed to a match phase interrupt). But I think we will need this ability to simulate the execution for proper compilation database support so we might as well just do it.

**Comment by akddv** [comment]
Thanks for your quick answer.
I close this issue since support for compilation database is already in your future plans anyway.

**Comment by boris-kolpackov** [comment]
I think let's keep this issue open since this functionality can be useful on its own (e.g., too see what needs to be done to bring the project up to date) and is also the first step in the proper compilation database support.

**Comment by akddv** [comment]
Thanks for your quick action.
I tested the staged toolchain, but was not able to create a compile database using `$ b -v |& compiledb`
Below is a minimized example of the issue I believe I am facing. Consider the simple project:

> .
> └── src
>     ├── build
>     │   ├── bootstrap.build
>     │   ├── config.build
>     │   └── root.build
>     ├── buildfile
>     ├── compo.cpp
>     ├── compo.h
>     └── hello.cpp

```
// src/hello.cpp
#include "compo.h"
int main() { say(); } 
```

```
// src/compo.h
void say();
```

```
// src/compo.cpp
#include "compo.h"
#include <iostream>
void say() { std::cout << "Hello World" << std::endl; }
```

```
# src/buildfile
exe{hello}: cxx{hello} cxx{compo}
./: exe{hello}
```

Running the command `$ b -v '{clean update}(src@src/exe{hello})'` will output:
> g++ -o src/hello.o -c -x c++ /home/ankur/Test/b2cdb/src/hello.cpp
> g++ -o src/compo.o -c -x c++ /home/ankur/Test/b2cdb/src/compo.cpp
> g++ -L /usr/local/lib -o src/hello src/hello.o src/compo.o

While adding the `-n` option will output only the following line:
> g++ -L /usr/local/lib -o src/hello src/hello.o src/compo.o

Hopefully this can help, I can provide a tarball if needed.

**Comment by boris-kolpackov** [comment]
Nice one. A *logical clean*, I wonder how many build systems actually support this...

Anyways, the fix is staged (you can upgrade by downloading the new script and running it with `--upgrade`). Let me know if there are any other issues.

**Comment by akddv** [comment]
Great, it now works well to produce compilation database, and as expected it is faster!
Thanks.
