### ISSUE TITLE
Libs will fail to link if we do not specify at least one symbol

### ISSUE THREAD

**Issue by wroyca** [build2/build2#231]
Libs will fail to link if we do not specify at least one symbol. For convenience, we should export a dummy symbol by default in export.hpp. e.g. ```LIBHELLO_SYMEXPORT void __libhello_sym_export__();```

```powershell
LINK : fatal error LNK1181: cannot open input file '..\hello-msvc\libhello\libhello\hello.dll.lib'
error: process link exited with code 1181
  info: command line: link /NOLOGO /MACHINE:x64 /INCREMENTAL:NO /DEFAULTLIB:shell32 /DEFAULTLIB:user32 /MANIFEST:EMBED /MANIFESTINPUT:..\hello-msvc\hello\hello\hello.exe.manifest /IMPLIB:..\hello-msvc\hello\hello\hello.exe.lib /OUT:..\hello-msvc\hello\hello\hello.exe ..\hello-msvc\hello\hello\hello.exe.obj ..\hello-msvc\libhello\libhello\hello.dll.lib
```

**Comment by Klaim** [comment]
We saw this issue several time in the past in the chat and I hit it several times too.
The issue here is that it's the behavior of the msvc toolchain linker that decides not to create the `.lib` file (containing the interface in the case of a dll) when there is no symbol exported.

In any way a dll not exporting any symbol makes no sense (or did you find a case where it's useful?), and the issue comes from msvc's toolchain (you can reproduce the same issue in visual studio with msbuild).

So not sure what `build2` can do about it, except maybe report earlier that the .lib was not generated (which is a very msvc-specific check)...

**Comment by wroyca** [comment]
> So not sure what build2 can do about it, except maybe report earlier that the .lib was not generated (which is a very msvc-specific check)...

We can provide a dummy export on ordinal 1. I agree that an empty DLL is useless, the dummy is just convenient if someone (like me) forgets this requirement and accidentally link a "to do" target library

**Comment by boris-kolpackov** [comment]
I agree with @Klaim, this is a peculiarity of the MSVC toolchain and a DLL that doesn't export any symbols is not very useful (I believe even `DllMain()` has to be exported). Exporting some dummy symbol is a bad idea, IMO, since it just masks what is most likely a bug. But we can check if the import library is absent after running `link.exe` and issue some helpful diagnostics. I've implemented this and it will be available on the next restage.

**Comment by wroyca** [comment]
Now available with https://github.com/build2/build2/commit/a6f5ad72f4c751cd62566de227a7cbe89ff3af26
