### ISSUE TITLE
Facilitate the ability to create custom targets with custom commands

### ISSUE THREAD

**Issue by wroyca** [build2/build2#239]
Build2 doesn't have a friendly way to add custom targets with custom commands execution, this make building any serious projects extremely difficult. :sweat: 

Example:

Assembling .S files:

```
using c

define s: file
s{*}: extension = s

s = $name(s{*})

exe{sum}: {h c}{*} obje{$s}

for n: $s
  obje{$(n).o}: s{$n}

obje{~'/(.*)/'}: s{~'/\1/'}
{{
  diag c $<
  $c.path -o $path($>) -c -x assembler $path($<)
}}
```

-- This should be as simple as, e.g.
```
for n: $s
  cc -o $(n).o -c -x assembler $(n).s
```

XML Compilation:

```
define xml: file
xml{*}: extension = xml
xml = $name(xml{*})

cxx{out}: xml
{{
  glib-compile-resources --generate-source $path($<[0]) --sourcedir $out_root/echo
}}
```

-- This should be a simple out-in but it led to a 3 hour conversation thread with 122 replies on slack as we tried to get it to work, and even then we can't get it to work because we are greeted with the cryptic "echo/buildfile:12:1: error: unable to deduce low-verbosity script diagnostics name".

Alternative?  Specify a build event? 

```
exe{echo}: {hxx ixx txx cxx xml}{**} $libs : event{pre}
{{
    for n: $xml
       glib-compile-resources --generate-source ($n).xml --sourcedir $out_root/echo
}}

||

exe{echo}: {hxx ixx txx cxx xml}{**} $libs : event{post}
{{
    for n: $xml
       glib-compile-resources --generate-source ($n).xml --sourcedir $out_root/echo
}}

||

exe{echo}: {hxx ixx txx cxx xml}{**} $libs : event{pre post}
{{
    for n: $xml
       glib-compile-resources --generate-source ($n).xml --sourcedir $out_root/echo
}}
```

Less restriction on bash sandbox?

```
cxx{out}: xml
{{
  cd resources
  glib-compile-resources --generate-source foo.xml
}}
```

commands?

```
exe{echo}: {hxx ixx txx cxx xml}{**} $libs : exec
{{
    for n: $xml
       glib-compile-resources --generate-source ($n).xml --sourcedir $out_root/echo
}}
```

what else ? 

...

**Comment by boris-kolpackov** [comment]
I believe there are three main reasons for your experience:

1. Since we want to support Windows as a first-class citizen, we cannot rely on  a shell (e.g., `bash`) like `make` does. As a result, we had to invent our own POSIX-like shell (which originated in Testscript). While at it we also fixed a few annoying mistakes like having to quote all variable expansion or not failing on error by default. So there is some initial learning curve.

2. In `build2` we try to make sure ad hoc recipes are correct by construction as much as possible when it comes to change tracking. So whereas in something like `make` you can whip a recipe in a few minutes and then spend couple of years cleaning out various corner cases (like "why didn't my outputs get updates when I changed the command line") in `build2` this "effort" is front-loaded.

3. We still don't have proper documentation for ad hoc recipes. But we do have announcements with examples (plus some real-world usage in packages like Qt) that I think should allow one to at least get started. Not sure if you read through those:

https://build2.org/release/0.13.0.xhtml#adhoc-recipe

https://build2.org/release/0.14.0.xhtml#adhoc-rules

https://build2.org/release/0.15.0.xhtml#dyndep

Plus let me also mention the "Low verbosity diagnostics rework" item from the `NEWS` file:

https://github.com/build2/build2/blob/master/NEWS#L28

**Comment by wroyca** [comment]
> I believe there are three main reasons for your experience:
> 
>     1. Since we want to support Windows as a first-class citizen, we cannot rely on  a shell (e.g., `bash`) like `make` does. As a result, we had to invent our own POSIX-like shell (which originated in Testscript). While at it we also fixed a few annoying mistakes like having to quote all variable expansion or not failing on error by default. So there is some initial learning curve.
> 
>     2. In `build2` we try to make sure ad hoc recipes are correct by construction as much as possible when it comes to change tracking. So whereas in something like `make` you can whip a recipe in a few minutes and then spend couple of years cleaning out various corner cases (like "why didn't my outputs get updates when I changed the command line") in `build2` this "effort" is front-loaded.
> 
>     3. We still don't have proper documentation for ad hoc recipes. But we do have announcements with examples (plus some real-world usage in packages like Qt) that I think should allow one to at least get started. Not sure if you read through those:
> 
> 
> https://build2.org/release/0.13.0.xhtml#adhoc-recipe
> 
> https://build2.org/release/0.14.0.xhtml#adhoc-rules
> 
> https://build2.org/release/0.15.0.xhtml#dyndep
> 
> Plus let me also mention the "Low verbosity diagnostics rework" item from the `NEWS` file:
> 
> https://github.com/build2/build2/blob/master/NEWS#L28

Thanks! The "Low verbosity diagnostics rework" was actually the real wall I was hitting, not understanding how it worked until I stumbled upon "diag gen $>" in one of the repositories here, which was like finding the graal
