### ISSUE TITLE
[BUG] Fetching of private repositories fails to authenticate

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#251]
When specifying a repository in `repositories.manifest` that is private and requires authentication, `build2` will not honour the credentials stored in the credential manager (specified in the git config as `credential.helper = xxx`). Meaning manually cloning the repository works, but when `build2` tries to fetch it then it fails:

`curl: (22) The requested URL returned error: 401`

This is problematic as one either has to:
1. Pass `--curl-option="-u <username>:<password/PAT>"` (bad, don't want to repeat or store credentials in repository, eg. when it's automated in a script).
2. Pass `--curl-option="-u <username>"` and enter the password/PAT when prompted (bad because it's repetitive and again, not possible to automize).

I've been investigating this a bit to see if it's possible to have `curl` (or tell it to) use the username and/or email stored in gits config & the credential manager to authenticate, but since I'm not too familiar with `curl` and related things I've come up short so far.

**Comment by boris-kolpackov** [comment]
For background, the reason we use `curl` to query the `git` repository is to detect its protocol capabilities (dumb vs smart HTTP, etc) in order to minimize the amount of history we fetch. See this command for an overview: https://github.com/build2/bpkg/blob/master/bpkg/fetch-git.cxx#L543

I would really like to avoid querying the git configuration for credentials or some such since I strongly believe we will be cleaning out various corner cases for the rest of our lives. Other alternatives that I can think of off the top of my head:

1. Avoid the query by hardcoding the expected result for some well-known `git` hosting locations (`github`, `gitlab`).

2. If we get 401, assume the worst (dumb HTTP).

3. Provide an option to specify a custom result for a URL prefix. Something like `--git-capabilities https://github.com=smart`.

**Comment by helmesjo** [comment]
**Note**: In my case it's dev.azure.com.

**Comment by boris-kolpackov** [comment]
An alternative arrangement that won't require hardcoding (and thus maintaining) any information:

1. If we get 401, assume smart HTTP. I think if authentication is involved, this is unlikely to be dumb HTTP. But we can also issue a note in the verbose mode (`-v`) about this and suggest the use of the `--git-capabilities` option to override, if necessary.

2. Provide an option to specify a custom result for a URL prefix as above.

**Comment by boris-kolpackov** [comment]
This has been implemented and is available in the latest staged version of the toolchain. Please test and report any issues.

**Comment by helmesjo** [comment]
I can confirm that this solved our issue. Thank you!
