### ISSUE TITLE
`bpkg-build` `--upgrade` slow

### ISSUE THREAD

**Issue by boris-kolpackov** [build2/build2#278]
From slack chat:

> Some workflow changes have meant that I now want to occasionally run `bdep sync -u -d some_package` to upgrade immediate dependencies, but this command is taking multiple minutes to run due to a deep recursion through the dependency tree.

> This is the fundamental callstack from a quick profile I did when I first ran into it. Beyond what's shown, `upgrade_dependencies` then recurses to a depth of ~20, which at a guess would map to the package dependency graph depth? It feels about right for my project + boost.

```
  Function                                                                             Module  Inclusive Time  Exclusive Time
-----------------------------------------------------------------------------------------------------------------------------
  bpkg::main                                                                           bpkg    19933.68        0.00          
     bpkg::pkg_build                                                                   bpkg    19933.68        0.00          
        static bool `bpkg::pkg_build'::`602'::<lambda_35>::operator()                  bpkg    19933.68        0.00          
           static class std::optional<bpkg::evaluate_result> bpkg::evaluate_recursive  bpkg    19933.68        0.00          
              static class std::optional<bool> bpkg::upgrade_dependencies              bpkg    19933.68        0.00          
```

> The actual processing time comes down to low level things like string manipulation/mem alloc/sqlite calls, but it very much gives the impression that it's the number of visits that's the real killer.

I wonder if we have any pruning mechanism in place in order not to traverse the same sub-graphs repeatedly?

**Comment by boris-kolpackov** [comment]
The latest staged version includes an optimization to prune already traversed dependency sub-graphs. @kamrann could you give it a try and see if it make any difference?

**Comment by kamrann** [comment]
I'll grab this now and try it out. 

Note that I tested briefly with the [boost-dependency test repo](https://github.com/boris-kolpackov/boost-dependency) yesterday, and this issue is very prominent there without making any changes.

**Comment by kamrann** [comment]
Okay, so did brief tests with both my project and `boost-dependency`, performance issue seems well and truly fixed! What was taking minutes is down to a second or two. Nice job!

One new bug though, not sure to what extent it's related to the changes. As an added test I tried to add `https://pkg.cppget.org/1/alpha` to the `repositories.manifest` in `boost-dependency` (it currently has only `/stable`, and since the latest version of the `boost` packages are not in there, I wanted to add it so I could test upgrading them to `1.81`). However after editing the manifest, `bdep sync -u` yields:
```
Assertion failed: i == deps.end (), file C:\build2\build\build2-toolchain-0.16-a.0\bpkg-0.16.0-a.0.20230523092557.13582557aaa1\bpkg\pkg-build-collect.cxx, line 5892
error: process bpkg terminated abnormally: aborted
```

And one other thing to note in case it's of interest. Before the fix, profiling showed that the bulk of the time was spent with strings - in particular, `butl::uuid::c_string`'s call to `sprintf`, and memory allocations for `bpkg::version` constructor/destructor. Obviously the algorithmic fix renders this somewhat irrelevant, but still since I guess there will remain cases with a lot of repeated visits, some kind of caching of these strings might be worth looking into as a general optimization.

**Comment by boris-kolpackov** [comment]
Ok, the assert has been fixed in the latest staged version but in the process we've discovered that upgrading to the latest Boost with `bdep sync -u` on the `boost-dependency` project  also takes several minutes. We will look into this shortly as it also doesn't seem reasonable.
