### ISSUE TITLE
Change `cxx.std=latest` mapping for MSVC

### ISSUE THREAD

**Issue by boris-kolpackov** [build2/build2#34]
Currently we map our `latest` `cxx.std` value to VC's `/std:c++latest`. However, in the 16.1 release a fairly risky feature was enabled by default in this mode (quoting the [release notes]( https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.1.0)):

```
* Lambda support has been overhauled, addressing a large number of
  long-standing bugs. This change is enabled by default when using
  /std:c++latest. In other /std:c++* language modes and under the default
  mode, the new parser can be enabled via /experimental:newLambdaProcessor,
  e.g. /std:c++17 /experimental:newLambdaProcessor.
```

I've chatted to MS folks about it suggesting that they add the `/std:experimental` mode for such cases. However, the feedback I got is that `/std:c++latest` is that mode. So in this light we should probably only map our `experimental` value to `/std:c++latest`, mapping `latest` to `c++17`.

What do you think?

**Comment by Klaim** [comment]
I think it would make sense, though I also think that instead of using the `latest` name (which I find ambiguous) it would be more useful to distinguish: 
 - the latests features implemented (which means potentially experimental);
 - the latest STANDARD;

This is basically what gcc and clang do if I understand correctly (their latest means the latest standard).

So if you have these two cases named differently, then:
 - the latest available/implemented standard should be the default, indeed;
 - "experimental" should be whatever flags enabling all experimental features (I guess to be discussed in case of activating selectively experimental features);

Suggestions:
 - latest standard: "cxx.std=current-standard/latest-standard" (I'm not sure it's a good idea to keep "latest" as it's ambiguous);
 - all features implemented: "cxx.std=experimental";

That opens the possibility (maybe in the future) to have some specific setup when the standard version is slightly modified (like gnu++17).

**Comment by masterspline** [comment]
> Suggestions:
>
>   * latest standard: "cxx.std=current-standard/latest-standard" (I'm
>     not sure it's a good idea to keep "latest" as it's ambiguous);
>   * all features implemented: "cxx.std=experimental";
>
I vote for "current_stable" and "experimental" for unambiguity and rich
choice. Make "latest" deprecated (with warning), currently equal to
"current_stable" and remove "latest" 5-10 years later. "Current_stable"
means latest stable for this build2 release (in case for strange
situation when too old build2 will be used with new compiler and latest
for build2 (ex. c++17) will not be last stable supported standard for
compiler, ex. c++20). So current_stable will change on each standard
update (once each 3 years).

P.S. It looks like build2 will require to change quite often and latest
build2 will be best choice to use, so it's time to think about
compatibility right now, but this is offtopic.

**Comment by boris-kolpackov** [comment]
Just to clarify, out `latest` value means C++ features from the latest available standard *that are considered sufficiently stable*. This maps quite well to GCC/Clang `-std=c++2a` (and similar `c++Nx` values) since for experimental/WIP features these implementations normally use separate switches (like, say, `-fmodules`).

In particular, I don't think *the latest published standard* semantics is particularly useful or even achievable since these days most compilers cannot claim full conformance for many years while being perfectly usable.

**Comment by Klaim** [comment]
There is no difference in gcc and clang between `-std=c++17` and `-std=c++1z`, or is there? The only thing that differs, if I remember correctly, is that `-std=c++2a` will be available before the next standard is published, while the corresponding `-std=c++20` will be available after the standard is published and then `-std=c++2a` then becomes an alias to `-std=c++20` (and is marked deprecated) and `-std=c++2b` is then open, etc.
That's what I understand from the spec: https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html#C-Dialect-Options

My understanding is that these flags provide exactly *what is implemented of this specific standard* (or soon-to-be-standard* which is indeed the best you can expect. In this context, what I call "latest-standard" is the last published standard as implemented by the compiler, but not more than this standard, so this is indeed different from msvc's latest and matches build2's latest - and gcc/clang don't have this flag, I thought they implemented it recently but I can't find where I read that so let's assume it doesn't exist. 

> latest available standard that are considered sufficiently stable

Looks like we agree on the correct meaning of `cxx.std=latest`. It would then mean:
 - gcc-9/clang-9: `-std=c++17` (not `-std=c++1z` as it's deprecated)
 - msvc-16: `/std=c++17` (instead of `/std:c++latest` currently)

Then if I understand correctly, `cxx.std=experimental` (at least for now) would mean:
 - gcc-9/clang-9: `-std=c++2a` (until it's an actual standard and available in the compiler)
 - msvc-16: `/std:c++latest `
 (the question of how to activate specific TSs features is another issue to open, I forgot about that)

If this is all correct, I agree with the change. 
I would have not used the term "latest" alone but that's not important I think now.

**Comment by boris-kolpackov** [comment]
In Clang and GCC the `c++Nx` (where `N` is the number and `x` is a letter; for example `c++1x`, `c++1y`, `c++2a`) are tentative placeholders for the to-be-published standard names. Once the standard is published they simply become (deprecated) aliases for the final name. Note also (and this is important for our discussion) that Clang/GCC do not wait to add the final name until the support is feature-complete. Which means that there are versions that recognize, say, `c++17` without actually implementing it completely.

Regarding the stability guarantees of such placeholder names, this is what GCC has to say about `c++2a`:

> The next revision of the ISO C++ standard, tentatively planned for 2020. Support is highly experimental, and will almost certainly change in incompatible ways in future releases. 

And here is for Clang:

> Clang has **experimental** support for some proposed features of the C++ standard following C++17, provisionally named C++2a. Note that support for these features may change or be removed without notice, as the draft C++2a standard evolves.

So on the face of it, `experimental` feels like a better fit for these than `latest`. However our experience using these tentative standards in GCC 4.9-9.0 and in Clang 3.7-8.0 shows that they are fairly usable and stable with truly experimental/WIP features enabled with separate options (for example, `-fmodules-ts`).

Note also that both of the above quotes talk about *C++2a features* being experimental and subject to change, not the overall stability of the compiler in this mode. And this is exactly the problem with what VC folks did in 16.1: they enabled an experimental feature that affected previous standards (and which broke existing code that doesn't use any C++2a features).

**Comment by boris-kolpackov** [comment]
Another `c++-latest`-only breakage in 16.3.0: https://developercommunity.visualstudio.com/content/problem/748081/new-internal-compiler-error-in-1630-msc1cpp-line-1.html

**Comment by boris-kolpackov** [comment]
Ok, for the 0.12.0 release we have remapped `latest` to `c++17` for MSVC 16.0 and up (for older versions of MSVC we still map to `c++latest` where appropriate).
