### ISSUE TITLE
Some problems using buildfile exportation

### ISSUE THREAD

**Issue by kamrann** [build2/build2#357]
Just going off the limited info in the 0.16 release notes for this, so may me missing some understanding, but I've hit two apparent and easy to reproduce issues.

1. `b clean` appears to be broken for any package exporting a buildfile. After adding `foo.build` to `/build/export` any attempt to `b clean` the root directory of such a package, or `bdep clean` the containing project, yields: `error: no rule to clean libhello\build\export\buildfile{foo}@..\build\cfg-name\libhello\build\export\`.
2. Maybe this wasn't intended usage, but there seems to be a strange issue when importing a buildfile exported from a different project (initialized in a shared configuration). From my testing, it will work so long as the importing buildfile first imports a target from the exporting package, eg. `import libs += libhello%lib{hello}` precedes `import libhello%buildfile{foo}`. Without the prior library import, I get: `error: unable to read imported buildfile build\export\foo.build: no such file or directory`. Testing in the case of a single multi-package project didn't seem to have the same caveat.

**Comment by boris-kolpackov** [comment]
Uh, yes, both are bugs, thanks for the report. Both are now fixed in the latest staged toolchain. I am going to close this issue but feel free to reopen/comment if something still doesn't work for you.

BTW, if you want to see a somewhat realistic use of exported buildfiles, you can find one example here: https://github.com/boris-kolpackov/cheriot-rtos/blob/build2/build2/export/rules.build2
