### ISSUE TITLE
Improvement: should level 1 build diagnostics show output targets instead/in addition to input?

### ISSUE THREAD

**Issue by Klaim** [build2/build2#40]
When `in` build2 module generates a file, a log outputs the template file being processed. It would be useful to also see the file being generated (not sure if complete or relative path would be useful).

In particular, when generating several files using the same `.in` file, it is impossible to know which file have been generated. It's even less clear when it's an incremental build.

Example from our prototypes using build2, our buildfile:

```
# ...
for node_source : hxx{**}
{
#...
  ./: lib{$node_name}: hxx{$node_header} cxx{$node_lib} $dependencies
  cxx{$node_lib} : build/dl/in{lib}
  cxx{$node_lib} :
  {
    node_name = "$node_name"
  }
}
```

This works as expected but the output is not clear on what is generated:

```
> b
mkdir ..\..\build-msvc\protox-nodes\fsdir{cpp\}
in cpp\build\dl\lib.cpp.in
in cpp\build\dl\lib.cpp.in
in cpp\build\dl\lib.cpp.in
in cpp\build\dl\lib.cpp.in
in cpp\build\dl\lib.cpp.in
in cpp\build\dl\lib.cpp.in
in cpp\build\dl\lib.cpp.in
in cpp\build\dl\lib.cpp.in
in cpp\build\dl\lib.cpp.in
in cpp\build\dl\lib.cpp.in
in cpp\build\dl\lib.cpp.in
...
```

Something like this (fake) would be useful:

```
> b
mkdir ..\..\build-msvc\protox-nodes\fsdir{cpp\}
in cpp\build\dl\lib.cpp.in  -> ..\..\build-msvc\protox-nodes\cpp\lib-a.cpp
in cpp\build\dl\lib.cpp.in  -> ..\..\build-msvc\protox-nodes\cpp\lib-b.cpp
in cpp\build\dl\lib.cpp.in  -> ..\..\build-msvc\protox-nodes\cpp\lib-c.cpp
in cpp\build\dl\lib.cpp.in  -> ..\..\build-msvc\protox-nodes\cpp\lib-d.cpp
in cpp\build\dl\lib.cpp.in  -> ..\..\build-msvc\protox-nodes\cpp\lib-e.cpp
in cpp\build\dl\lib.cpp.in  -> ..\..\build-msvc\protox-nodes\cpp\lib-f.cpp
in cpp\build\dl\lib.cpp.in  -> ..\..\build-msvc\protox-nodes\cpp\lib-g.cpp
in cpp\build\dl\lib.cpp.in  -> ..\..\build-msvc\protox-nodes\cpp\lib-h.cpp
in cpp\build\dl\lib.cpp.in  -> ..\..\build-msvc\protox-nodes\cpp\lib-i.cpp
in cpp\build\dl\lib.cpp.in  -> ..\..\build-msvc\protox-nodes\cpp\lib-j.cpp
in cpp\build\dl\lib.cpp.in  -> ..\..\build-msvc\protox-nodes\cpp\lib-k.cpp
...
```

**Comment by boris-kolpackov** [comment]
If you add `-v`, you should see the more detailed command line:

```
> b -v
in libtest\version.hxx.in >libtest\version.hxx
```

**Comment by Klaim** [comment]
Ok, but why is this in a more verbose mode? I usually use verbose mode when I see a problem or for CI output.

It looks to me that it would be more useful to see the generated file by default. Or do you see cases where it makes more sense to do as currently?

**Comment by boris-kolpackov** [comment]
In the non-verbose output we normally show either input or output not to produce unnecessary noise (we also show target names instead of actual file paths). Whether it is input or output is decided on the case by case basis according to what feels natural. For example, when compiling C/C++ we show input (source file) while when linking we show output (executable, library, etc). For `in` we went with the same approach as for compilation.

In case of the C/C++ compilation this is normally not a problem because there is a 1:1 mapping and showin the output (object file) would be just adding noise. The same goes for `in`: in most cases there is 1:1 mapping.

This is a problem, however, in your case where you produce multiple output from the same `.in` file. Currently I don't have any good ideas of how we could address this.

**Comment by boris-kolpackov** [comment]
BTW, one notable build system that does something similar (abbreviated output) is the Linux kernel. They, however, always show the output, for example:

```
GEN   security/apparmor/net_names.h
YACC    scripts/genksyms/parse.tab.h
YACC    scripts/genksyms/parse.tab.c
LEX    scripts/genksyms/lex.lex.c
CC      certs/load_uefi.o
AR      certs/built-in.a
LINK   /usr/src/linux/tools/objtool/objtool
```

One solution would be to adopt this model. One sticky point is what to show for multi-output rules (notice the two `YACC` lines above).

**Comment by Klaim** [comment]
My current opinion on which one, input or output, to show for `in` would be output only (in non-verbose mode). 
This is mainly because if I see in log that a file is generated, I can find how it was generated in the sources, no need to reproduce the build to see it in verbose, so I can deduce myself what happened (if it was surprising).
However if I see in log that a template file is used to generate something I don't know, I can't reproduce that step without doing a cleanup + build verbose, and looking at the buildfiles won't help telling me which one was generated.
(to clarify it's not a big issue, of course).

> One solution would be to adopt this model. 

Looks fine to me.

> One sticky point is what to show for multi-output rules (notice the two YACC lines above).

Personally I'm fine with each output having it's line, though if you want to make it less verbose, maybe reducing the  length of the path in some ways would help (like keeping just the file's directory).

**Comment by boris-kolpackov** [comment]
I am reluctant to make an ad hoc fix in just the `in` module and which is only really needed if one is generating multiple files from a single template. So let's wait and see if any better idea and/or new information comes up.

**Comment by boris-kolpackov** [comment]
Related: https://lists.build2.org/archives/users/2019-July/000661.html

**Comment by boris-kolpackov** [comment]
Ok, I think we have two options here:

1. Show only the output, like the Linux kernel.

2. Show both source and output.

I suppose there is a third option which would be some combination of the two. For example, show only the output if file stems of source and output match and otherwise show both.

The first option has the following drawbacks:

1. While it's easy to mentally map, say, an object file name to a source file name, it's still a mental step.

2. While in the Linux kernel they can probably require that object file stems always match source file stems, in `build2` we don't have such a requirement and, in fact, there are use-case where it is handy to build different object files from the same source file,
in which case we must necessarily have different stems:

```
obje{driver-small}: cxx{driver}
{
  cxx.poptions += -DSMALL
}

obje{driver-large}: cxx{driver}
{
  cxx.poptions += -DLARGE
}
```

3. In the canonical development setup with `bdep` we have a number of out-of-source build configurations but normally build from the source directory. In this case, if we show the source relative to the current working directory, it will have the minimal directory qualification. While for the output it will have to include the output directory. For example:

```
c++ cxx{driver}
c++ details/cxx{driver}
```

```
c++ ../hello-gcc/obje{driver}
c++ ../hello-gcc/details/obje{driver}
```

So based on that I am leaning toward showing both in he following form:

```
c++ cxx{driver} -> ../hello-gcc/obje{driver}
c++ details/cxx{driver} -> ../hello-gcc/details/obje{driver}
```

IMO, the nice thing about this form is that it show the information in the diminishing usefulness order and it should hopefully be easy to "scan-out" the first two fields (type of compilation and source file).

**Comment by Klaim** [comment]
I agree this form would be useful.

**Comment by boris-kolpackov** [comment]
Here is an example of the old and new forms (I am capturing this together with some thoughts in anticipation of future "why don't you just" type of discussions):

Old:

```
mkdir ../libhello-gcc/libhello/fsdir{libhello/}
version libhello/in{version}
mkdir ../libhello-gcc/libhello/tests/fsdir{basics/}
c++ libhello/cxx{hello}@../libhello-gcc/libhello/libhello/
c++ libhello/cxx{hello}@../libhello-gcc/libhello/libhello/
c++ tests/basics/cxx{driver}@../libhello-gcc/libhello/tests/basics/
ar ../libhello-gcc/libhello/libhello/liba{hello}
ld ../libhello-gcc/libhello/libhello/libs{hello}
ld ../libhello-gcc/libhello/tests/basics/exe{driver}
ln ../libhello-gcc/libhello/tests/basics/exe{driver} -> tests/basics/
```

New:

```
mkdir -> ../libhello-gcc/libhello/fsdir{libhello/}
version libhello/in{version} -> ../libhello-gcc/libhello/libhello/hxx{version}
mkdir -> ../libhello-gcc/libhello/tests/fsdir{basics/}
c++ libhello/cxx{hello} -> ../libhello-gcc/libhello/libhello/objs{hello}
c++ libhello/cxx{hello} -> ../libhello-gcc/libhello/libhello/obja{hello}
c++ tests/basics/cxx{driver} -> ../libhello-gcc/libhello/tests/basics/obje{driver}
ld -> ../libhello-gcc/libhello/libhello/libs{hello}
ar -> ../libhello-gcc/libhello/libhello/liba{hello}
ld -> ../libhello-gcc/libhello/tests/basics/exe{driver}
ln ../libhello-gcc/libhello/tests/basics/exe{driver} -> tests/basics/
```

A couple of thoughts:

1. `->` in `mkdir` definitely looks strange but I think it's worth keeping for regularity.

2. I was thinking of perhaps aligning/tabulating the columns to make things more readable but then realized that if any lines get wrapped (like in my Emacs window), tabulation will make things significantly worse.

3. Perhaps a better way to make things more readable is to use color and/or bold text. For example, we could make the tool name and `->` bold for better legibility.

Another question is what the "undo" diagnostics should look like for operations like `clean` and `uninstall`. Ideally we would want something consistent/symmetrical. The `install` diagnostics will look like this:

```
install ../libhello-gcc/libhello/libhello/libs{hello} -> /usr/lib/
install ../libhello-gcc/libhello/libhello/liba{hello} -> /usr/lib/
```

And it feels like the best corresponding `uninstall` diagnostics would be:

```
install ../libhello-gcc/libhello/libhello/libs{hello} <- /usr/lib/
install ../libhello-gcc/libhello/libhello/liba{hello} <- /usr/lib/
```

Here, in a sense, `->` means "do" and `<-` means "undo".

And if we go with the above `uninstall` diagnostics, then `clean` would be (admittedly somewhat strange-looking):

```
rm <- ../libhello-gcc/libhello/tests/basics/exe{driver}
rm <- ../libhello-gcc/libhello/tests/basics/obje{driver}
rmdir <- ../libhello-gcc/libhello/tests/fsdir{basics/}
rm <- ../libhello-gcc/libhello/libhello/liba{hello}
rm <- ../libhello-gcc/libhello/libhello/libs{hello}
rm <- ../libhello-gcc/libhello/libhello/objs{hello}
rm <- ../libhello-gcc/libhello/libhello/obja{hello}
rm <- ../libhello-gcc/libhello/libhello/hxx{version}
rmdir <- ../libhello-gcc/libhello/fsdir{libhello/}
```

In a way, if we were to embrace the Windows/Mac OS desktop metaphor, we could also do:

```
rm Trash <- ../libhello-gcc/libhello/tests/basics/exe{driver}
```

**Comment by Klaim** [comment]
> 2. I was thinking of perhaps aligning/tabulating the columns to make things more readable but then realized that if any lines get wrapped (like in my Emacs window), tabulation will make things significantly worse.

I don't think it's necessary. Although if it if felt necessary there is the possibility to just make sure the first word is spaced to reach, say, at least 6 characters  (arbitrary guess) - then if the word is longer it is treated like in your example with just a space separator. That would give something like this:

```
mkdir -> ../libhello-gcc/libhello/fsdir{libhello/}
version libhello/in{version} -> ../libhello-gcc/libhello/libhello/hxx{version}
mkdir -> ../libhello-gcc/libhello/tests/fsdir{basics/}
c++   -> libhello/cxx{hello} -> ../libhello-gcc/libhello/libhello/objs{hello}
c++   -> libhello/cxx{hello} -> ../libhello-gcc/libhello/libhello/obja{hello}
c++   -> tests/basics/cxx{driver} -> ../libhello-gcc/libhello/tests/basics/obje{driver}
ld    -> ../libhello-gcc/libhello/libhello/libs{hello}
ar    -> ../libhello-gcc/libhello/libhello/liba{hello}
ld    -> ../libhello-gcc/libhello/tests/basics/exe{driver}
ln    ../libhello-gcc/libhello/tests/basics/exe{driver} -> tests/basics/
custom_code_generator -> ../libhello-gcc/libhello/libhello/file{somefile}
```

But as said I don't think that's necessary. Issues with size of console will appear anyway as long as the paths are long.

> Another question is what the "undo" diagnostics should look like for operations like clean and uninstall. Ideally we would want something consistent/symmetrical.

Personally, I would just pre-append "revert " before the name of the operation and call it a day. And then maybe specialize in some cases like `uninstall`. The advantage of `revert ...` is that it's super easy to spot and understand - it also adapts to whatever custom compiler/generator name will be used by people.
To be clear I'm talking about the output log only, not commands that are basically "undo".

> Here, in a sense, -> means "do" and <- means "undo".

In my head `->` means "generates" or "outputs", and `<-` feels like "inject back into" (which only works for your "rm Trash" example).
I'm not convinced that `<-` for "undo" makes sense here, but that's just first glance opinion.

> And if we go with the above uninstall diagnostics, then clean would be (admittedly somewhat strange-looking):

My first instinct is that it's too obscure and hard to spot when scanning logs with the bare eye. I would suggest to ask the community to get more feedback about that idea?

**Comment by boris-kolpackov** [comment]
> Personally, I would just pre-append "revert " before the name of the operation and call it a day.

Yes, I thought about this but in the end I believe this will be too much information. Consider:

```
revert c++ libhello/cxx{hello} -> ../libhello-gcc/libhello/libhello/objs{hello}
```

The key goals we try to achieve here are: (1) provide just enough information to understand what's going on and (2) make this information easy for a human to scan . And, in case of `clean`, I don't think it's useful to know which source file each object file comes from.

Perhaps a better option is to make the format a bit less regular by omitting `->` if there is no input file. Consider:

```
c++ libhello/cxx{hello} -> ../libhello-gcc/libhello/libhello/objs{hello}
c++ libhello/cxx{hello} -> ../libhello-gcc/libhello/libhello/obja{hello}
ld ../libhello-gcc/libhello/libhello/libs{hello}
ar ../libhello-gcc/libhello/libhello/liba{hello}
```

I think given the context (i.e., the tool name and the target type), it will be easy for a human to infer what is what.

In this case `clean` stays the same as before:

```
rm ../libhello-gcc/libhello/libhello/liba{hello}
rm ../libhello-gcc/libhello/libhello/libs{hello}
rm ../libhello-gcc/libhello/libhello/objs{hello}
rm ../libhello-gcc/libhello/libhello/obja{hello}
```

But we can still keep the directory for the `uninstall` case (because I think it's useful to know from where things are being uninstalled):

```
uninstall ../libhello-gcc/libhello/libhello/libs{hello} <- /usr/lib/
uninstall ../libhello-gcc/libhello/libhello/liba{hello} <- /usr/lib/
```

BTW, another operation that will benefit from omitting `->` is `test`:

```
test ../libhello-gcc/libhello/tests/basics/exe{driver}
```

But we can use it if there is a `testscript` involved (which is, in a sense, an input for the target being tested):

```
test tests/basics/testscript -> ../libhello-gcc/libhello/tests/basics/exe{driver}
```

> I would suggest to ask the community to get more feedback about that idea?

I don't want to turn this into a protracted bikesheding session and would rather ask the community to provide feedback on the completed design, once it's available in the staged toolchain.

**Comment by Klaim** [comment]
> Perhaps a better option is to make the format a bit less regular by omitting -> if there is no input file.

Works for me!

> Overall, this will be a fairly minor change from the current format, which is a good thing.

Indeed, it solves my initial issue generally without impacting much.

> I don't want to turn this into a protracted bikesheding session and would rather ask the community to provide feedback on the completed design, once it's available in the staged toolchain.

Fair enough. :)

**Comment by boris-kolpackov** [comment]
Ok, this has been implemented and is now available in the latest staged toolchain.

**Comment by boris-kolpackov** [comment]
This fix has been out for a while now without any new complaints so far, so I am going to close this issue to keep things organized. But feel free to reopen if there are still any issues.
