### ISSUE TITLE
Fails to bootstrap with musl

### ISSUE THREAD

**Issue by numberZero** [build2/build2#50]
I have Void Linux, with musl as the C library. `build2` fails to bootstrap here, due to following problems:

1. musl lacks `execinfo.h` and the corresponding functions. Alternatives exist but I had none installed; they require explicit linking anyway.
2. musl provides `strndup`, but `libpkgconf/bsdstubs.c:115` defines it (as `static`) nevertheless, which leads to compilation error.

**Comment by boris-kolpackov** [comment]
Thanks for the report.

> musl lacks `execinfo.h`
> musl provides `strndup`

We could come up with a tweak in `libbutl/backtrace.cxx` to detect this and not define `LIBBUTL_BACKTRACE` and do something similar for `strndup` if there were something like `__MUSL__` or some other way to detect it. But apparently there isn't. So I am not sure what we can do here. Ideas are welcome.

**Comment by boris-kolpackov** [comment]
Thinking out loud, I wonder if there is some musl-specific header which we can sniff out with `__has_include`, at least for the newer compilers?

**Comment by numberZero** [comment]
Maybe something like `defined(linux) && !defined(__GLIBC__)`?

**Comment by numberZero** [comment]
For `strndup`, defining it as weak extern instead of static should work.

**Comment by boris-kolpackov** [comment]
I believe we have fixed the backtrace issue in master. We've also worked around the `strndup` issue which turns out to actually be a bug in musl (it only check the definition and not the value of `_POSIX_C_SOURCE` before enabling `strndup`). All these fixes have been staged and it would be great if you can try them out and confirm things work now: https://build2.org/community.xhtml#stage

Also, to answer my own question about detecting musl by a presence of a header: there doesn't appear to be anything musk-specific in `include/`, in fact, none of the installed headers even have the word `musl` in them.

**Comment by boris-kolpackov** [comment]
We are about to release 0.12.0 and would be great to confirm whether this works or not.

**Comment by numberZero** [comment]
Seems to work; but build fails later on #62.

**Comment by boris-kolpackov** [comment]
Thanks for testing. It would be great if you could try to build the entire toolchain using the install script. 0.12.0 has been released and includes these fixes so you could try the stable version: https://build2.org/install.xhtml#unix

**Comment by boris-kolpackov** [comment]
Assuming fixed. Please feel free to reopen if there are still issues.
