### ISSUE TITLE
contributing.md

### ISSUE THREAD

**Issue by patrick-fromberg** [build2/build2#57]
contributing.md file would be helpful.

**Comment by boris-kolpackov** [comment]
Yes, that's been on our TODO list for some time. Are there any specific areas (submitting issues, development setup,  submitting patches, legal stuff, etc) that you are looking for?

**Comment by patrick-fromberg** [comment]
This project is extremely important and I am sure many would like to contribute. But it is a difficult project too and I think this is why not many are contributing. I am considering it but do not really know where to start. The reason why I came here that there is no build system I like even though I had some hope in QBS - but that was discontinued.

**Comment by boris-kolpackov** [comment]
Thanks for the feedback. Yes, setting up the environment to develop `build2` itself is unfortunately not straightforward primarily because we use it (including `bdep`) for its own development which often poses chicken-and-egg kinds of problems. But I am planning to write this down at some point.

Also, there are quite a few other ways to contribute besides hacking the `build2` core itself (listed in the order of increasing difficulty):

1. Try using `build2` in your projects, run into bugs/missing features (inevitable at this stage) and file issues. Then help us come up with a solution by providing feedback, doing research, testing fixes, etc; #51 is a great example of this process. 

2. Package external projects for `build2`, preferable the ones that you want to use as dependencies in your own projects (we are strong believers in the "scratch your own itch" workflow). We've setup a community for this purpose: https://github.com/build2-packaging/

3. Write build system modules for source code generators, other programming languages, etc. This is still somewhat experimental, but in the 0.12.0 release we are adding support for build system modules and some folks have already started experimenting with it: https://lists.build2.org/archives/users/2019-August/000670.html and continues here: https://lists.build2.org/archives/users/2019-September/000673.html

In the next couple of days I will create the `CONTRIBUTING.md` file and will move these points there as a start.

**Comment by patrick-fromberg** [comment]
This is the info I was looking for, thanks.

**Comment by boris-kolpackov** [comment]
I am going to reopen this for the meantime (until we move things to `CONTRIBUTING.md`).

**Comment by boris-kolpackov** [comment]
Added to all the `build2` repositories `CONTRIBUTING.md`  that points to our [Community](https://build2.org/community.xhtml) page where we now have the Contributing section. Also created #58.
