### ISSUE TITLE
When packaging, cannot use upstream test source files

### ISSUE THREAD

**Issue by J-Vernay** [build2/build2#95]
Hello, I am a newcomer to `build2`, so I am not sure whether it is a bug or a misunderstanding from my side.

When trying to package a library (namely `utf8proc`) , I encountered an error **no rule to update .../c{test}**.
Here is a minimal setup to encounter the same bug:

```bash
bdep new -l c -t lib mylib
cd mylib
### project modification
# putting the test source file in an upstream directory
mkdir upstream
mv tests/basics/driver.c upstream/
# modifying main buildfile to exclude upstream directory
echo "./: {*/ -build/ -upstream/} doc{README.md} manifest" > buildfile
# modifying testcase buildfile to find the new location of the test source file
(echo "import libs = mylib%lib{mylib}" && echo "" && echo "exe{driver}: {h c}{../../upstream/**} $libs testscript{**}") > tests/basics/buildfile 
### project configuration
bdep init -C @gcc c config.c=gcc
### project building
b
```
Output:
```
error: no rule to update ../mylib-gcc/mylib/upstream/c{driver}
  info: re-run with --verbose=4 for more information
  info: while applying rule c.compile to update ../mylib-gcc/mylib/upstream/obje{driver}
  info: while applying rule c.link to update ../mylib-gcc/mylib/tests/basics/exe{driver}
  info: while applying rule alias to update ../mylib-gcc/mylib/tests/dir{basics/}
  info: while applying rule alias to update ../mylib-gcc/mylib/dir{tests/}
  info: while applying rule alias to update ../mylib-gcc/dir{mylib/}
info: failed to update ../mylib-gcc/dir{mylib/}
```

I was expecting these modifications not to break the building, because it is just relocating a source file.

**Comment by boris-kolpackov** [comment]
In `build2` things work best when a `buildfile` builds things in its directory and, potentially, its subdirectories, without lateral jumps. And your case is a good demonstration of nuances that arise from such arrangements.

The reason you get the error is because `mylib/tests/` is actually a subproject (see [Testing](https://build2.org/build2/doc/build2-build-system-manual.xhtml#intro-operations-test) in the build system manual for reasons/details) and so from the `tests/basics/buildfile`'s point of view you are trying to compile a source file out of project, which the C compiler rule doesn't allow (for good reasons).

Now on how to fix this: the recommended approach for what you are trying to achieve is to use symlinks to "pull" source files from `upstream/` into the `build2` project structure. See [Using Symlinks in `build2` Projects](https://build2.org/article/symlinks.xhtml) for details. There are also quite a few examples of this approach in [build2-packaging](https://github.com/build2-packaging/), for example, [`zlib`](https://github.com/build2-packaging/zlib). Finally, see [build2-packaging/README](https://github.com/build2-packaging/README) for some other tips and tricks.

**Comment by J-Vernay** [comment]
Ok thank you! I was basing my work on the fmt packaging which does not use symlinks ( https://github.com/build2-packaging/fmt/blob/master/fmt/buildfile ) so I encountered this error.
Thanks to this, now it works locally. (I have issues with the CI but this is not this issue's topic)
